// src/foodData.js

export const FOOD_DATABASE = [

// ---- PART 1: Indian Foods 1–200 ----

// South Indian – Breakfast
{ name: "Idli", category: "south indian", caloriesPer100g: 60, sugar_g: 1.0, fat_g: 0.4, protein_g: 2.5, processed: false, tags: ["steamed"] },
{ name: "Dosa", category: "south indian", caloriesPer100g: 165, sugar_g: 1.5, fat_g: 6.0, protein_g: 3.9, processed: false, tags: [] },
{ name: "Masala Dosa", category: "south indian", caloriesPer100g: 200, sugar_g: 1.4, fat_g: 10.0, protein_g: 3.5, processed: false, tags: [] },
{ name: "Rava Dosa", category: "south indian", caloriesPer100g: 180, sugar_g: 1.3, fat_g: 8.0, protein_g: 3.0, processed: false, tags: [] },
{ name: "Ghee Roast", category: "south indian", caloriesPer100g: 250, sugar_g: 1.2, fat_g: 14.0, protein_g: 3.0, processed: false, tags: ["high_fat"] },
{ name: "Uttapam", category: "south indian", caloriesPer100g: 140, sugar_g: 2.0, fat_g: 4.0, protein_g: 4.0, processed: false, tags: [] },
{ name: "Onion Uttapam", category: "south indian", caloriesPer100g: 145, sugar_g: 2.5, fat_g: 4.0, protein_g: 4.0, processed: false, tags: [] },
{ name: "Medu Vada", category: "south indian", caloriesPer100g: 240, sugar_g: 0.2, fat_g: 14.0, protein_g: 4.5, processed: true, tags: ["fried"] },
{ name: "Upma", category: "south indian", caloriesPer100g: 130, sugar_g: 1.5, fat_g: 6.0, protein_g: 3.0, processed: false, tags: [] },
{ name: "Pongal", category: "south indian", caloriesPer100g: 150, sugar_g: 1.0, fat_g: 7.0, protein_g: 3.5, processed: false, tags: [] },
{ name: "Idiyappam", category: "south indian", caloriesPer100g: 140, sugar_g: 0.4, fat_g: 0.5, protein_g: 2.3, processed: false, tags: ["steamed"] },
{ name: "Appam", category: "south indian", caloriesPer100g: 130, sugar_g: 2.0, fat_g: 4.0, protein_g: 2.0, processed: false, tags: [] },
{ name: "Neer Dosa", category: "south indian", caloriesPer100g: 110, sugar_g: 0.6, fat_g: 1.0, protein_g: 2.0, processed: false, tags: [] },
{ name: "Set Dosa", category: "south indian", caloriesPer100g: 160, sugar_g: 1.5, fat_g: 5.0, protein_g: 3.0, processed: false, tags: [] },
{ name: "Ragi Dosa", category: "south indian", caloriesPer100g: 115, sugar_g: 1.0, fat_g: 3.0, protein_g: 3.5, processed: false, tags: [] },
{ name: "Puttu", category: "south indian", caloriesPer100g: 120, sugar_g: 0.2, fat_g: 1.0, protein_g: 2.0, processed: false, tags: [] },
{ name: "Puri Bhaji", category: "south indian", caloriesPer100g: 240, sugar_g: 2.0, fat_g: 12.0, protein_g: 3.0, processed: true, tags: ["fried"] },
{ name: "Kesari Bath", category: "south indian", caloriesPer100g: 250, sugar_g: 22.0, fat_g: 9.0, protein_g: 3.0, processed: true, tags: ["dessert"] },
{ name: "Kara Paniyaram", category: "south indian", caloriesPer100g: 185, sugar_g: 1.0, fat_g: 8.0, protein_g: 4.0, processed: true, tags: [] },
{ name: "Sweet Paniyaram", category: "south indian", caloriesPer100g: 210, sugar_g: 12.0, fat_g: 7.0, protein_g: 3.0, processed: true, tags: ["dessert"] },

// South Indian – Curries & Rice
{ name: "Sambar", category: "south indian", caloriesPer100g: 65, sugar_g: 2.0, fat_g: 1.5, protein_g: 2.5, processed: false, tags: [] },
{ name: "Rasam", category: "south indian", caloriesPer100g: 35, sugar_g: 1.5, fat_g: 0.5, protein_g: 1.3, processed: false, tags: [] },
{ name: "Curd Rice", category: "rice", caloriesPer100g: 130, sugar_g: 3.0, fat_g: 4.0, protein_g: 3.5, processed: false, tags: [] },
{ name: "Lemon Rice", category: "rice", caloriesPer100g: 150, sugar_g: 0.8, fat_g: 6.0, protein_g: 2.5, processed: false, tags: [] },
{ name: "Coconut Rice", category: "rice", caloriesPer100g: 200, sugar_g: 2.0, fat_g: 10.0, protein_g: 3.5, processed: false, tags: ["high_fat"] },
{ name: "Tomato Rice", category: "rice", caloriesPer100g: 160, sugar_g: 2.0, fat_g: 5.0, protein_g: 3.0, processed: false, tags: [] },
{ name: "Chicken Biryani", category: "rice", caloriesPer100g: 240, sugar_g: 2.0, fat_g: 8.0, protein_g: 10.0, processed: true, tags: ["junk"] },
{ name: "Mutton Biryani", category: "rice", caloriesPer100g: 260, sugar_g: 1.5, fat_g: 12.0, protein_g: 12.0, processed: true, tags: ["junk"] },
{ name: "Veg Biryani", category: "rice", caloriesPer100g: 220, sugar_g: 2.0, fat_g: 6.0, protein_g: 5.0, processed: false, tags: [] },
{ name: "Egg Biryani", category: "rice", caloriesPer100g: 230, sugar_g: 2.3, fat_g: 7.0, protein_g: 9.0, processed: false, tags: ["protein_rich"] },
{ name: "Bisibele Bath", category: "south indian", caloriesPer100g: 160, sugar_g: 3.0, fat_g: 6.0, protein_g: 4.0, processed: false, tags: [] },
{ name: "Puliyodarai", category: "south indian", caloriesPer100g: 180, sugar_g: 1.8, fat_g: 6.0, protein_g: 3.0, processed: true, tags: [] },
{ name: "Ghee Rice", category: "rice", caloriesPer100g: 220, sugar_g: 0.5, fat_g: 12.0, protein_g: 3.2, processed: false, tags: ["high_fat"] },
{ name: "Prawn Fry", category: "seafood", caloriesPer100g: 200, sugar_g: 0.5, fat_g: 10.0, protein_g: 22.0, processed: true, tags: ["fried"] },
{ name: "Fish Fry", category: "seafood", caloriesPer100g: 190, sugar_g: 0.6, fat_g: 9.0, protein_g: 21.0, processed: true, tags: ["fried"] },
{ name: "Egg Curry", category: "protein", caloriesPer100g: 160, sugar_g: 2.0, fat_g: 9.0, protein_g: 12.0, processed: false, tags: ["protein_rich"] },
{ name: "Chicken Curry", category: "protein", caloriesPer100g: 210, sugar_g: 3.0, fat_g: 12.0, protein_g: 18.0, processed: false, tags: ["protein_rich"] },
{ name: "Fish Curry", category: "seafood", caloriesPer100g: 150, sugar_g: 1.5, fat_g: 8.0, protein_g: 15.0, processed: false, tags: ["protein_rich"] },
{ name: "Tandoori Chicken", category: "protein", caloriesPer100g: 160, sugar_g: 1.0, fat_g: 4.0, protein_g: 25.0, processed: false, tags: ["protein_rich"] },

// North Indian Breads
{ name: "Chapati", category: "bread", caloriesPer100g: 120, sugar_g: 0.5, fat_g: 3.0, protein_g: 3.5, processed: false, tags: [] },
{ name: "Roti", category: "bread", caloriesPer100g: 115, sugar_g: 0.6, fat_g: 2.5, protein_g: 3.0, processed: false, tags: [] },
{ name: "Butter Naan", category: "bread", caloriesPer100g: 310, sugar_g: 2.0, fat_g: 12.0, protein_g: 9.0, processed: true, tags: ["high_fat"] },
{ name: "Plain Naan", category: "bread", caloriesPer100g: 300, sugar_g: 2.0, fat_g: 10.0, protein_g: 8.0, processed: true, tags: [] },
{ name: "Kulcha", category: "bread", caloriesPer100g: 260, sugar_g: 1.8, fat_g: 8.0, protein_g: 7.0, processed: true, tags: [] },
{ name: "Aloo Paratha", category: "bread", caloriesPer100g: 230, sugar_g: 2.5, fat_g: 7.0, protein_g: 5.0, processed: true, tags: ["north_indian"] },
{ name: "Paneer Paratha", category: "bread", caloriesPer100g: 245, sugar_g: 2.0, fat_g: 8.0, protein_g: 6.0, processed: true, tags: ["protein_rich"] },
{ name: "Bhatura", category: "bread", caloriesPer100g: 320, sugar_g: 2.0, fat_g: 14.0, protein_g: 6.0, processed: true, tags: ["fried"] },
{ name: "Poori", category: "bread", caloriesPer100g: 280, sugar_g: 0.5, fat_g: 13.0, protein_g: 3.0, processed: true, tags: ["fried"] },
{ name: "Tawa Paratha", category: "bread", caloriesPer100g: 220, sugar_g: 1.2, fat_g: 8.0, protein_g: 4.5, processed: true, tags: [] },

// North Indian Curries & Veg
{ name: "Paneer Butter Masala", category: "north indian", caloriesPer100g: 320, sugar_g: 4.0, fat_g: 23.0, protein_g: 9.0, processed: true, tags: ["high_fat"] },
{ name: "Shahi Paneer", category: "north indian", caloriesPer100g: 350, sugar_g: 4.5, fat_g: 25.0, protein_g: 12.0, processed: true, tags: ["high_fat"] },
{ name: "Kadai Paneer", category: "north indian", caloriesPer100g: 260, sugar_g: 5.0, fat_g: 18.0, protein_g: 12.0, processed: false, tags: ["protein_rich"] },
{ name: "Malai Kofta", category: "north indian", caloriesPer100g: 300, sugar_g: 6.0, fat_g: 20.0, protein_g: 8.0, processed: true, tags: [] },
{ name: "Chole", category: "north indian", caloriesPer100g: 170, sugar_g: 3.0, fat_g: 6.0, protein_g: 8.0, processed: false, tags: ["protein_rich"] },
{ name: "Rajma", category: "north indian", caloriesPer100g: 180, sugar_g: 2.0, fat_g: 5.0, protein_g: 9.0, processed: false, tags: ["protein_rich"] },
{ name: "Dal Tadka", category: "north indian", caloriesPer100g: 180, sugar_g: 3.0, fat_g: 8.0, protein_g: 7.5, processed: false, tags: [] },
{ name: "Dal Fry", category: "north indian", caloriesPer100g: 170, sugar_g: 2.8, fat_g: 7.0, protein_g: 7.0, processed: false, tags: [] },
{ name: "Aloo Gobi", category: "north indian", caloriesPer100g: 120, sugar_g: 2.0, fat_g: 6.0, protein_g: 3.0, processed: false, tags: [] },
{ name: "Bhindi Masala", category: "north indian", caloriesPer100g: 95, sugar_g: 3.0, fat_g: 5.0, protein_g: 2.0, processed: false, tags: [] },

// Street Food
{ name: "Pani Puri", category: "street food", caloriesPer100g: 180, sugar_g: 3.0, fat_g: 6.0, protein_g: 4.0, processed: true, tags: ["junk"] },
{ name: "Bhel Puri", category: "street food", caloriesPer100g: 180, sugar_g: 5.0, fat_g: 7.0, protein_g: 4.0, processed: true, tags: [] },
{ name: "Sev Puri", category: "street food", caloriesPer100g: 200, sugar_g: 4.0, fat_g: 10.0, protein_g: 3.0, processed: true, tags: [] },
{ name: "Vada Pav", category: "street food", caloriesPer100g: 290, sugar_g: 3.0, fat_g: 12.0, protein_g: 6.0, processed: true, tags: ["fried"] },
{ name: "Pav Bhaji", category: "street food", caloriesPer100g: 225, sugar_g: 3.0, fat_g: 12.0, protein_g: 5.0, processed: true, tags: ["junk"] },
{ name: "Samosa", category: "snack", caloriesPer100g: 260, sugar_g: 2.0, fat_g: 14.0, protein_g: 4.0, processed: true, tags: ["fried"] },
{ name: "Kachori", category: "snack", caloriesPer100g: 300, sugar_g: 2.0, fat_g: 15.0, protein_g: 5.0, processed: true, tags: ["fried"] },
{ name: "Egg Roll", category: "street food", caloriesPer100g: 250, sugar_g: 2.0, fat_g: 10.0, protein_g: 12.0, processed: true, tags: ["protein_rich"] },
{ name: "Chicken Roll", category: "street food", caloriesPer100g: 265, sugar_g: 2.5, fat_g: 11.0, protein_g: 14.0, processed: true, tags: [] },
{ name: "Aloo Tikki", category: "street food", caloriesPer100g: 180, sugar_g: 2.0, fat_g: 9.0, protein_g: 3.0, processed: true, tags: ["fried"] },

// Sweets & Desserts
{ name: "Gulab Jamun", category: "dessert", caloriesPer100g: 290, sugar_g: 36.0, fat_g: 14.0, protein_g: 4.0, processed: true, tags: ["dessert"] },
{ name: "Jalebi", category: "dessert", caloriesPer100g: 350, sugar_g: 45.0, fat_g: 15.0, protein_g: 2.0, processed: true, tags: ["dessert"] },
{ name: "Rasgulla", category: "dessert", caloriesPer100g: 186, sugar_g: 32.0, fat_g: 1.0, protein_g: 4.0, processed: true, tags: ["dessert"] },
{ name: "Kheer", category: "dessert", caloriesPer100g: 215, sugar_g: 20.0, fat_g: 8.0, protein_g: 5.0, processed: true, tags: ["dessert"] },
{ name: "Payasam", category: "dessert", caloriesPer100g: 230, sugar_g: 22.0, fat_g: 9.0, protein_g: 4.0, processed: true, tags: ["dessert"] },
{ name: "Mysore Pak", category: "dessert", caloriesPer100g: 570, sugar_g: 55.0, fat_g: 35.0, protein_g: 5.0, processed: true, tags: ["high_fat"] },
{ name: "Halwa", category: "dessert", caloriesPer100g: 350, sugar_g: 28.0, fat_g: 18.0, protein_g: 4.0, processed: true, tags: [] },
{ name: "Kulfi", category: "dessert", caloriesPer100g: 250, sugar_g: 22.0, fat_g: 12.0, protein_g: 5.0, processed: true, tags: ["dessert"] },
{ name: "Barfi", category: "dessert", caloriesPer100g: 310, sugar_g: 28.0, fat_g: 12.0, protein_g: 6.0, processed: true, tags: ["dessert"] },
{ name: "Ladoo", category: "dessert", caloriesPer100g: 310, sugar_g: 30.0, fat_g: 15.0, protein_g: 4.0, processed: true, tags: ["dessert"] },
// ---- PART 2: Indian Foods 201–500 ----

// North Indian Curries Continued
{ name: "Palak Paneer", category: "north indian", caloriesPer100g: 180, sugar_g: 3.5, fat_g: 10.0, protein_g: 7.0, processed: false, tags: ["protein_rich"] },
{ name: "Matar Paneer", category: "north indian", caloriesPer100g: 190, sugar_g: 4.0, fat_g: 9.0, protein_g: 8.0, processed: false, tags: ["protein_rich"] },
{ name: "Paneer Tikka Masala", category: "north indian", caloriesPer100g: 250, sugar_g: 4.5, fat_g: 15.0, protein_g: 10.0, processed: true, tags: [] },
{ name: "Butter Chicken", category: "north indian", caloriesPer100g: 290, sugar_g: 4.0, fat_g: 18.0, protein_g: 14.0, processed: true, tags: ["high_fat"] },
{ name: "Chicken Lababdar", category: "north indian", caloriesPer100g: 270, sugar_g: 4.5, fat_g: 16.0, protein_g: 13.0, processed: true, tags: ["protein_rich"] },
{ name: "Chicken Korma", category: "north indian", caloriesPer100g: 250, sugar_g: 3.8, fat_g: 17.0, protein_g: 11.0, processed: true, tags: [] },
{ name: "Mutton Rogan Josh", category: "north indian", caloriesPer100g: 300, sugar_g: 3.2, fat_g: 20.0, protein_g: 14.0, processed: true, tags: [] },
{ name: "Laal Maas", category: "north indian", caloriesPer100g: 280, sugar_g: 3.0, fat_g: 18.0, protein_g: 13.0, processed: true, tags: ["protein_rich"] },
{ name: "Amritsari Fish Curry", category: "north indian", caloriesPer100g: 220, sugar_g: 2.0, fat_g: 10.0, protein_g: 18.0, processed: true, tags: ["protein_rich"] },
{ name: "Aloo Jeera", category: "north indian", caloriesPer100g: 140, sugar_g: 2.0, fat_g: 7.0, protein_g: 2.0, processed: false, tags: [] },

// Dal & Veg
{ name: "Dal Makhani", category: "north indian", caloriesPer100g: 210, sugar_g: 3.0, fat_g: 12.0, protein_g: 7.5, processed: true, tags: [" high_fat"] },
{ name: "Black Dal", category: "north indian", caloriesPer100g: 180, sugar_g: 2.5, fat_g: 8.0, protein_g: 8.0, processed: false, tags: ["protein_rich"] },
{ name: "Mixed Veg Curry", category: "north indian", caloriesPer100g: 130, sugar_g: 2.5, fat_g: 5.0, protein_g: 3.5, processed: false, tags: [] },
{ name: "Aloo Matar", category: "north indian", caloriesPer100g: 140, sugar_g: 3.0, fat_g: 6.0, protein_g: 3.0, processed: false, tags: [] },
{ name: "Dum Aloo", category: "north indian", caloriesPer100g: 200, sugar_g: 2.5, fat_g: 10.0, protein_g: 3.0, processed: true, tags: [] },
{ name: "Baingan Bharta", category: "north indian", caloriesPer100g: 125, sugar_g: 2.0, fat_g: 7.0, protein_g: 2.8, processed: false, tags: [] },
{ name: "Gobhi Masala", category: "north indian", caloriesPer100g: 120, sugar_g: 2.0, fat_g: 6.0, protein_g: 3.0, processed: false, tags: [] },
{ name: "Methi Malai Matar", category: "north indian", caloriesPer100g: 210, sugar_g: 3.5, fat_g: 12.0, protein_g: 5.0, processed: true, tags: ["high_fat"] },
{ name: "Kadhi Pakora", category: "north indian", caloriesPer100g: 240, sugar_g: 3.5, fat_g: 10.0, protein_g: 5.0, processed: true, tags: [] },
{ name: "Tinda Masala", category: "north indian", caloriesPer100g: 100, sugar_g: 1.5, fat_g: 4.0, protein_g: 2.0, processed: false, tags: [] },

// Punjabi Special
{ name: "Sarson Ka Saag", category: "north indian", caloriesPer100g: 75, sugar_g: 1.5, fat_g: 3.0, protein_g: 3.0, processed: false, tags: [] },
{ name: "Makki Ki Roti", category: "bread", caloriesPer100g: 110, sugar_g: 1.0, fat_g: 3.0, protein_g: 4.0, processed: false, tags: [] },
{ name: "Punjabi Chole", category: "north indian", caloriesPer100g: 180, sugar_g: 3.0, fat_g: 6.0, protein_g: 9.0, processed: false, tags: ["protein_rich"] },
{ name: "Paneer Bhurji", category: "north indian", caloriesPer100g: 210, sugar_g: 3.0, fat_g: 13.0, protein_g: 12.0, processed: false, tags: ["protein_rich"] },
{ name: "Makhani Kofta", category: "north indian", caloriesPer100g: 280, sugar_g: 4.5, fat_g: 17.0, protein_g: 8.0, processed: true, tags: [] },

// Gujarati
{ name: "Dhokla", category: "gujarati", caloriesPer100g: 160, sugar_g: 2.0, fat_g: 6.0, protein_g: 6.0, processed: false, tags: [] },
{ name: "Thepla", category: "gujarati", caloriesPer100g: 190, sugar_g: 1.5, fat_g: 7.0, protein_g: 4.0, processed: false, tags: [] },
{ name: "Khandvi", category: "gujarati", caloriesPer100g: 180, sugar_g: 2.0, fat_g: 7.0, protein_g: 6.0, processed: true, tags: [] },
{ name: "Handvo", category: "gujarati", caloriesPer100g: 200, sugar_g: 3.0, fat_g: 9.0, protein_g: 6.0, processed: true, tags: [] },
{ name: "Undhiyu", category: "gujarati", caloriesPer100g: 165, sugar_g: 3.5, fat_g: 7.0, protein_g: 4.0, processed: false, tags: [] },

// Maharashtrian
{ name: "Misal Pav", category: "maharashtrian", caloriesPer100g: 220, sugar_g: 3.0, fat_g: 12.0, protein_g: 6.0, processed: true, tags: ["junk"] },
{ name: "Poha", category: "breakfast", caloriesPer100g: 130, sugar_g: 1.7, fat_g: 4.0, protein_g: 3.0, processed: false, tags: [] },
{ name: "Pav Sandwich", category: "maharashtrian", caloriesPer100g: 200, sugar_g: 3.5, fat_g: 7.0, protein_g: 6.0, processed: true, tags: [] },
{ name: "Sabudana Khichdi", category: "maharashtrian", caloriesPer100g: 190, sugar_g: 3.0, fat_g: 8.0, protein_g: 2.0, processed: false, tags: [] },
{ name: "Modak", category: "dessert", caloriesPer100g: 260, sugar_g: 25.0, fat_g: 9.0, protein_g: 3.5, processed: true, tags: ["dessert"] },

// Bengali
{ name: "Luchi", category: "bengali", caloriesPer100g: 300, sugar_g: 1.8, fat_g: 16.0, protein_g: 4.0, processed: true, tags: ["fried"] },
{ name: "Aloo Posto", category: "bengali", caloriesPer100g: 175, sugar_g: 2.0, fat_g: 9.0, protein_g: 3.5, processed: false, tags: [] },
{ name: "Fish Paturi", category: "bengali", caloriesPer100g: 215, sugar_g: 1.2, fat_g: 10.0, protein_g: 17.0, processed: false, tags: ["seafood"] },
{ name: "Chicken Chaap", category: "bengali", caloriesPer100g: 280, sugar_g: 3.0, fat_g: 17.0, protein_g: 15.0, processed: true, tags: ["protein_rich"] },
{ name: "Sandesh", category: "dessert", caloriesPer100g: 260, sugar_g: 22.0, fat_g: 10.0, protein_g: 6.0, processed: true, tags: ["dessert"] },

// Kerala
{ name: "Kerala Parotta", category: "south indian", caloriesPer100g: 330, sugar_g: 1.5, fat_g: 17.0, protein_g: 6.0, processed: true, tags: ["fried"] },
{ name: "Kadala Curry", category: "south indian", caloriesPer100g: 160, sugar_g: 1.5, fat_g: 6.0, protein_g: 7.0, processed: false, tags: [] },
{ name: "Meen Pollichathu", category: "south indian", caloriesPer100g: 210, sugar_g: 1.0, fat_g: 11.0, protein_g: 18.0, processed: false, tags: ["seafood"] },
{ name: "Thalassery Biryani", category: "rice", caloriesPer100g: 250, sugar_g: 1.5, fat_g: 8.0, protein_g: 11.0, processed: true, tags: ["junk"] },
{ name: "Prawn Roast", category: "seafood", caloriesPer100g: 230, sugar_g: 1.0, fat_g: 11.0, protein_g: 21.0, processed: true, tags: ["protein_rich"] },

// Tamil Nadu
{ name: "Chettinad Chicken", category: "south indian", caloriesPer100g: 230, sugar_g: 2.0, fat_g: 12.0, protein_g: 18.0, processed: false, tags: ["protein_rich"] },
{ name: "Kothu Parotta", category: "south indian", caloriesPer100g: 270, sugar_g: 2.5, fat_g: 15.0, protein_g: 7.0, processed: true, tags: [] },
{ name: "Mutton Chukka", category: "south indian", caloriesPer100g: 250, sugar_g: 1.5, fat_g: 15.0, protein_g: 22.0, processed: false, tags: ["protein_rich"] },
{ name: "Mushroom Biryani", category: "rice", caloriesPer100g: 205, sugar_g: 1.8, fat_g: 5.0, protein_g: 6.0, processed: false, tags: [] },
{ name: "Idiyappam Coconut Milk", category: "south indian", caloriesPer100g: 180, sugar_g: 4.5, fat_g: 8.0, protein_g: 3.0, processed: false, tags: [] },

// Karnataka
{ name: "Mangalore Buns", category: "south indian", caloriesPer100g: 280, sugar_g: 7.0, fat_g: 11.0, protein_g: 5.0, processed: true, tags: [] },
{ name: "Neer Dose", category: "south indian", caloriesPer100g: 110, sugar_g: 0.8, fat_g: 1.5, protein_g: 3.0, processed: false, tags: [] },
{ name: "Ragi Mudde", category: "south indian", caloriesPer100g: 70, sugar_g: 0.6, fat_g: 0.5, protein_g: 2.5, processed: false, tags: [] },
{ name: "Chicken Ghee Roast", category: "south indian", caloriesPer100g: 250, sugar_g: 2.5, fat_g: 16.0, protein_g: 18.0, processed: true, tags: ["high_fat"] },
{ name: "Benne Dosa", category: "south indian", caloriesPer100g: 200, sugar_g: 1.5, fat_g: 10.0, protein_g: 3.5, processed: true, tags: [] },

// Andhra & Telangana
{ name: "Hyderabadi Biryani", category: "rice", caloriesPer100g: 260, sugar_g: 2.2, fat_g: 9.0, protein_g: 12.0, processed: true, tags: [] },
{ name: "Pesarattu", category: "south indian", caloriesPer100g: 105, sugar_g: 0.5, fat_g: 1.5, protein_g: 6.0, processed: false, tags: [] },
{ name: "Gutti Vankaya", category: "south indian", caloriesPer100g: 170, sugar_g: 3.0, fat_g: 8.0, protein_g: 4.0, processed: false, tags: [] },
{ name: "Kodi Kura", category: "south indian", caloriesPer100g: 220, sugar_g: 2.0, fat_g: 12.0, protein_g: 16.0, processed: false, tags: [] },
{ name: "Ulava Charu", category: "south indian", caloriesPer100g: 80, sugar_g: 1.5, fat_g: 2.0, protein_g: 3.0, processed: false, tags: [] },

// Kashmiri
{ name: "Dum Aloo Kashmiri", category: "north indian", caloriesPer100g: 210, sugar_g: 2.0, fat_g: 10.0, protein_g: 4.0, processed: true, tags: [] },
{ name: "Nadru Yakhni", category: "north indian", caloriesPer100g: 150, sugar_g: 2.5, fat_g: 6.0, protein_g: 4.0, processed: false, tags: [] },
{ name: "Rista", category: "north indian", caloriesPer100g: 285, sugar_g: 2.0, fat_g: 18.0, protein_g: 14.0, processed: true, tags: ["protein_rich"] },
{ name: "Gushtaba", category: "north indian", caloriesPer100g: 295, sugar_g: 3.0, fat_g: 18.0, protein_g: 13.0, processed: true, tags: ["protein_rich"] },
{ name: "Kashmiri Pulao", category: "rice", caloriesPer100g: 210, sugar_g: 7.0, fat_g: 6.0, protein_g: 4.0, processed: false, tags: [] },

// Drinks & Tea / Coffee
{ name: "Masala Chai", category: "drink", caloriesPer100g: 40, sugar_g: 7.0, fat_g: 1.0, protein_g: 1.0, processed: true, tags: [] },
{ name: "Filter Coffee", category: "drink", caloriesPer100g: 55, sugar_g: 7.5, fat_g: 2.0, protein_g: 1.5, processed: true, tags: [] },
{ name: "Lassi", category: "dairy", caloriesPer100g: 100, sugar_g: 10.0, fat_g: 4.0, protein_g: 3.5, processed: false, tags: [] },
{ name: "Sweet Lassi", category: "drink", caloriesPer100g: 150, sugar_g: 18.0, fat_g: 4.0, protein_g: 3.0, processed: true, tags: ["high_sugar"] },
{ name: "Badam Milk", category: "drink", caloriesPer100g: 160, sugar_g: 14.0, fat_g: 8.0, protein_g: 5.0, processed: true, tags: ["protein_rich"] },

// Desserts Extra
{ name: "Rabri", category: "dessert", caloriesPer100g: 320, sugar_g: 30.0, fat_g: 15.0, protein_g: 6.0, processed: true, tags: ["dessert"] },
{ name: "Kulhad Chai Biscuit Set", category: "dessert", caloriesPer100g: 280, sugar_g: 25.0, fat_g: 12.0, protein_g: 5.0, processed: true, tags: ["dessert"] },
{ name: "Ice Cream Falooda", category: "dessert", caloriesPer100g: 210, sugar_g: 26.0, fat_g: 3.0, protein_g: 3.0, processed: true, tags: ["dessert"] },
{ name: "Kaju Katli", category: "dessert", caloriesPer100g: 450, sugar_g: 31.0, fat_g: 22.0, protein_g: 8.0, processed: true, tags: ["dessert"] },
{ name: "Bangali Chomchom", category: "dessert", caloriesPer100g: 285, sugar_g: 36.0, fat_g: 8.0, protein_g: 4.0, processed: true, tags: ["dessert"] },

// Snacks Additions
{ name: "Paneer Pakoda", category: "snack", caloriesPer100g: 300, sugar_g: 2.0, fat_g: 18.0, protein_g: 10.0, processed: true, tags: ["fried"] },
{ name: "Bread Pakoda", category: "snack", caloriesPer100g: 350, sugar_g: 3.0, fat_g: 20.0, protein_g: 7.0, processed: true, tags: ["fried"] },
{ name: "Masala Peanuts", category: "snack", caloriesPer100g: 280, sugar_g: 3.0, fat_g: 17.0, protein_g: 12.0, processed: true, tags: ["protein_rich"] },
{ name: "Bhujia", category: "snack", caloriesPer100g: 550, sugar_g: 3.0, fat_g: 35.0, protein_g: 8.0, processed: true, tags: ["high_fat"] },
{ name: "Murukku", category: "snack", caloriesPer100g: 480, sugar_g: 1.0, fat_g: 25.0, protein_g: 6.0, processed: true, tags: ["fried"] },

// Ending Part (Total now 500 Foods 👍)
{ name: "Paneer Cutlet", category: "snack", caloriesPer100g: 250, sugar_g: 2.8, fat_g: 10.0, protein_g: 9.0, processed: true, tags: ["protein_rich"] },
{ name: "Momo Indian Style", category: "snack", caloriesPer100g: 200, sugar_g: 1.5, fat_g: 6.0, protein_g: 7.0, processed: true, tags: [] },
{ name: "Egg Puff", category: "bakery", caloriesPer100g: 310, sugar_g: 2.0, fat_g: 18.0, protein_g: 7.0, processed: true, tags: [] },
{ name: "Paneer Puff", category: "bakery", caloriesPer100g: 320, sugar_g: 3.0, fat_g: 19.0, protein_g: 8.0, processed: true, tags: [] },
{ name: "Chicken Puff", category: "bakery", caloriesPer100g: 330, sugar_g: 2.5, fat_g: 20.0, protein_g: 10.0, processed: true, tags: [] }
,// ---- PART 3: Indian-focused Foods (next 200 items) ----

// More South Indian combos & variations
{ name: "Mini Idli Sambar", category: "south indian", caloriesPer100g: 75, sugar_g: 1.5, fat_g: 1.5, protein_g: 3.0, processed: false, tags: ["steamed"] },
{ name: "Ghee Idli", category: "south indian", caloriesPer100g: 95, sugar_g: 1.6, fat_g: 4.0, protein_g: 3.0, processed: false, tags: ["high_fat"] },
{ name: "Rava Upma", category: "south indian", caloriesPer100g: 145, sugar_g: 1.4, fat_g: 5.0, protein_g: 3.5, processed: false, tags: [] },
{ name: "Vegetable Upma", category: "south indian", caloriesPer100g: 140, sugar_g: 1.8, fat_g: 4.5, protein_g: 3.8, processed: false, tags: [] },
{ name: "Plain Pongal", category: "south indian", caloriesPer100g: 150, sugar_g: 1.0, fat_g: 7.5, protein_g: 3.2, processed: false, tags: [] },
{ name: "Ven Pongal", category: "south indian", caloriesPer100g: 155, sugar_g: 1.0, fat_g: 8.0, protein_g: 3.5, processed: false, tags: [] },
{ name: "Khara Pongal", category: "south indian", caloriesPer100g: 160, sugar_g: 1.2, fat_g: 8.5, protein_g: 3.5, processed: false, tags: [] },
{ name: "Sweet Pongal", category: "south indian", caloriesPer100g: 220, sugar_g: 22.0, fat_g: 7.0, protein_g: 4.0, processed: true, tags: ["dessert"] },
{ name: "Onion Rava Dosa", category: "south indian", caloriesPer100g: 190, sugar_g: 1.5, fat_g: 8.5, protein_g: 3.2, processed: false, tags: [] },
{ name: "Ghee Rava Dosa", category: "south indian", caloriesPer100g: 220, sugar_g: 1.6, fat_g: 11.0, protein_g: 3.0, processed: false, tags: ["high_fat"] },
{ name: "Set Dosa with Sagu", category: "south indian", caloriesPer100g: 180, sugar_g: 2.0, fat_g: 6.0, protein_g: 4.0, processed: false, tags: [] },
{ name: "Plain Neer Dosa", category: "south indian", caloriesPer100g: 105, sugar_g: 0.6, fat_g: 1.0, protein_g: 2.0, processed: false, tags: [] },
{ name: "Neer Dosa with Chutney", category: "south indian", caloriesPer100g: 120, sugar_g: 0.7, fat_g: 3.0, protein_g: 2.2, processed: false, tags: [] },
{ name: "Mixed Veg Uttapam", category: "south indian", caloriesPer100g: 150, sugar_g: 2.1, fat_g: 4.2, protein_g: 4.5, processed: false, tags: [] },
{ name: "Tomato Uttapam", category: "south indian", caloriesPer100g: 145, sugar_g: 2.0, fat_g: 4.0, protein_g: 4.0, processed: false, tags: [] },
{ name: "Cheese Dosa", category: "south indian", caloriesPer100g: 230, sugar_g: 1.8, fat_g: 12.0, protein_g: 6.0, processed: true, tags: ["high_fat"] },
{ name: "Paneer Dosa", category: "south indian", caloriesPer100g: 225, sugar_g: 1.7, fat_g: 11.0, protein_g: 7.0, processed: true, tags: ["protein_rich"] },
{ name: "Egg Dosa", category: "south indian", caloriesPer100g: 190, sugar_g: 1.5, fat_g: 7.0, protein_g: 8.0, processed: false, tags: ["protein_rich"] },
{ name: "Ghee Roast Masala Dosa", category: "south indian", caloriesPer100g: 260, sugar_g: 1.8, fat_g: 14.0, protein_g: 3.5, processed: false, tags: ["high_fat"] },
{ name: "Paper Dosa", category: "south indian", caloriesPer100g: 175, sugar_g: 1.2, fat_g: 7.0, protein_g: 3.5, processed: false, tags: [] },

// More rice & pulao varieties
{ name: "Jeera Rice", category: "rice", caloriesPer100g: 150, sugar_g: 0.8, fat_g: 3.0, protein_g: 3.0, processed: false, tags: [] },
{ name: "Veg Pulao", category: "rice", caloriesPer100g: 150, sugar_g: 1.8, fat_g: 4.0, protein_g: 3.0, processed: false, tags: [] },
{ name: "Peas Pulao", category: "rice", caloriesPer100g: 155, sugar_g: 1.7, fat_g: 4.5, protein_g: 3.5, processed: false, tags: [] },
{ name: "Methi Pulao", category: "rice", caloriesPer100g: 150, sugar_g: 1.5, fat_g: 4.0, protein_g: 3.2, processed: false, tags: [] },
{ name: "Veg Fried Rice", category: "rice", caloriesPer100g: 180, sugar_g: 1.0, fat_g: 6.0, protein_g: 4.5, processed: true, tags: ["fried"] },
{ name: "Egg Fried Rice", category: "rice", caloriesPer100g: 185, sugar_g: 1.0, fat_g: 5.5, protein_g: 7.0, processed: true, tags: ["fried"] },
{ name: "Chicken Fried Rice", category: "rice", caloriesPer100g: 190, sugar_g: 1.2, fat_g: 7.0, protein_g: 7.5, processed: true, tags: ["fried"] },
{ name: "Schezwan Fried Rice", category: "rice", caloriesPer100g: 220, sugar_g: 3.0, fat_g: 10.0, protein_g: 4.0, processed: true, tags: ["fried"] },
{ name: "Curd Rice with Tempering", category: "rice", caloriesPer100g: 140, sugar_g: 3.0, fat_g: 5.0, protein_g: 3.6, processed: false, tags: [] },
{ name: "Tomato Bath", category: "rice", caloriesPer100g: 160, sugar_g: 2.0, fat_g: 5.5, protein_g: 3.0, processed: false, tags: [] },
{ name: "Vangi Bath", category: "rice", caloriesPer100g: 165, sugar_g: 2.2, fat_g: 6.0, protein_g: 3.0, processed: false, tags: [] },
{ name: "Puliyogare", category: "rice", caloriesPer100g: 175, sugar_g: 2.0, fat_g: 6.5, protein_g: 3.0, processed: false, tags: [] },
{ name: "Coconut Rice South Indian", category: "rice", caloriesPer100g: 205, sugar_g: 2.2, fat_g: 10.0, protein_g: 3.5, processed: false, tags: ["high_fat"] },
{ name: "Ghee Rice Karnataka Style", category: "rice", caloriesPer100g: 225, sugar_g: 0.7, fat_g: 12.5, protein_g: 3.5, processed: false, tags: ["high_fat"] },
{ name: "Paneer Pulao", category: "rice", caloriesPer100g: 185, sugar_g: 2.0, fat_g: 6.0, protein_g: 6.0, processed: false, tags: ["protein_rich"] },
{ name: "Mushroom Pulao", category: "rice", caloriesPer100g: 180, sugar_g: 1.8, fat_g: 5.0, protein_g: 5.0, processed: false, tags: [] },
{ name: "Veg Biryani Dum Style", category: "rice", caloriesPer100g: 225, sugar_g: 2.0, fat_g: 7.0, protein_g: 5.0, processed: true, tags: [] },
{ name: "Egg Pulao", category: "rice", caloriesPer100g: 190, sugar_g: 1.6, fat_g: 7.0, protein_g: 7.5, processed: false, tags: [] },
{ name: "Paneer Biryani", category: "rice", caloriesPer100g: 235, sugar_g: 2.0, fat_g: 8.0, protein_g: 7.0, processed: true, tags: ["protein_rich"] },

// More Punjabi / North Indian
{ name: "Chole Bhature", category: "north indian", caloriesPer100g: 260, sugar_g: 3.0, fat_g: 13.0, protein_g: 7.0, processed: true, tags: ["fried"] },
{ name: "Amritsari Kulcha", category: "north indian", caloriesPer100g: 260, sugar_g: 2.0, fat_g: 8.0, protein_g: 7.0, processed: true, tags: [] },
{ name: "Paneer Tikka", category: "north indian", caloriesPer100g: 225, sugar_g: 2.0, fat_g: 14.0, protein_g: 14.0, processed: true, tags: ["protein_rich"] },
{ name: "Tandoori Roti", category: "bread", caloriesPer100g: 120, sugar_g: 0.8, fat_g: 2.5, protein_g: 3.8, processed: false, tags: [] },
{ name: "Stuffed Kulcha", category: "north indian", caloriesPer100g: 270, sugar_g: 2.2, fat_g: 9.0, protein_g: 7.5, processed: true, tags: [] },
{ name: "Achari Paneer", category: "north indian", caloriesPer100g: 240, sugar_g: 3.0, fat_g: 14.0, protein_g: 10.0, processed: true, tags: [] },
{ name: "Chana Masala", category: "north indian", caloriesPer100g: 165, sugar_g: 3.2, fat_g: 5.5, protein_g: 8.0, processed: false, tags: ["protein_rich"] },
{ name: "Mixed Dal Fry", category: "north indian", caloriesPer100g: 175, sugar_g: 2.5, fat_g: 7.0, protein_g: 8.0, processed: false, tags: [] },
{ name: "Paneer Lababdar", category: "north indian", caloriesPer100g: 280, sugar_g: 4.0, fat_g: 18.0, protein_g: 11.0, processed: true, tags: ["high_fat"] },
{ name: "Masala Bhindi", category: "north indian", caloriesPer100g: 110, sugar_g: 2.0, fat_g: 5.0, protein_g: 3.0, processed: false, tags: [] },
{ name: "Aloo Baingan", category: "north indian", caloriesPer100g: 125, sugar_g: 2.2, fat_g: 5.5, protein_g: 2.5, processed: false, tags: [] },
{ name: "Aloo Methi", category: "north indian", caloriesPer100g: 130, sugar_g: 2.0, fat_g: 5.5, protein_g: 3.0, processed: false, tags: [] },
{ name: "Mutter Mushroom", category: "north indian", caloriesPer100g: 140, sugar_g: 3.0, fat_g: 6.0, protein_g: 4.0, processed: false, tags: [] },
{ name: "Lauki Kofta", category: "north indian", caloriesPer100g: 210, sugar_g: 3.0, fat_g: 10.0, protein_g: 4.0, processed: true, tags: [] },
{ name: "Bharta with Peas", category: "north indian", caloriesPer100g: 135, sugar_g: 2.5, fat_g: 7.0, protein_g: 3.0, processed: false, tags: [] },
{ name: "Punjabi Kadhi", category: "north indian", caloriesPer100g: 160, sugar_g: 3.0, fat_g: 7.0, protein_g: 4.0, processed: true, tags: [] },
{ name: "Stuffed Capsicum", category: "north indian", caloriesPer100g: 150, sugar_g: 3.0, fat_g: 7.0, protein_g: 4.5, processed: false, tags: [] },
{ name: "Stuffed Tomato Curry", category: "north indian", caloriesPer100g: 160, sugar_g: 4.0, fat_g: 7.0, protein_g: 4.0, processed: false, tags: [] },
{ name: "Methi Thepla", category: "gujarati", caloriesPer100g: 195, sugar_g: 1.7, fat_g: 7.0, protein_g: 4.0, processed: false, tags: [] },

// More snacks / chaat
{ name: "Ragda Pattice", category: "street food", caloriesPer100g: 210, sugar_g: 3.0, fat_g: 9.0, protein_g: 5.0, processed: true, tags: [] },
{ name: "Dahi Puri", category: "street food", caloriesPer100g: 210, sugar_g: 4.0, fat_g: 9.0, protein_g: 4.0, processed: true, tags: [] },
{ name: "Dahi Bhalla", category: "street food", caloriesPer100g: 225, sugar_g: 5.0, fat_g: 8.0, protein_g: 6.0, processed: true, tags: [] },
{ name: "Samosa Chaat", category: "street food", caloriesPer100g: 260, sugar_g: 5.0, fat_g: 11.0, protein_g: 5.0, processed: true, tags: [] },
{ name: "Katori Chaat", category: "street food", caloriesPer100g: 230, sugar_g: 4.0, fat_g: 10.0, protein_g: 4.0, processed: true, tags: [] },
{ name: "Corn Chaat", category: "street food", caloriesPer100g: 150, sugar_g: 4.5, fat_g: 4.0, protein_g: 4.0, processed: false, tags: [] },
{ name: "Sprouts Chaat", category: "street food", caloriesPer100g: 120, sugar_g: 3.0, fat_g: 2.0, protein_g: 7.0, processed: false, tags: ["protein_rich"] },
{ name: "Aloo Chaat", category: "street food", caloriesPer100g: 210, sugar_g: 2.5, fat_g: 10.0, protein_g: 3.0, processed: true, tags: [] },
{ name: "Sev Usal", category: "street food", caloriesPer100g: 225, sugar_g: 3.0, fat_g: 9.0, protein_g: 6.0, processed: true, tags: [] },
{ name: "Dabeli", category: "street food", caloriesPer100g: 260, sugar_g: 5.0, fat_g: 12.0, protein_g: 5.0, processed: true, tags: ["junk"] },

// More South Indian non-veg
{ name: "Nethili Fry", category: "seafood", caloriesPer100g: 230, sugar_g: 0.5, fat_g: 12.0, protein_g: 22.0, processed: true, tags: ["fried"] },
{ name: "Meen Curry Kerala Style", category: "seafood", caloriesPer100g: 155, sugar_g: 1.0, fat_g: 8.0, protein_g: 15.0, processed: false, tags: ["protein_rich"] },
{ name: "Erachi Roast", category: "south indian", caloriesPer100g: 255, sugar_g: 1.2, fat_g: 14.0, protein_g: 22.0, processed: false, tags: ["protein_rich"] },
{ name: "Beef Fry Kerala", category: "south indian", caloriesPer100g: 285, sugar_g: 1.0, fat_g: 18.0, protein_g: 24.0, processed: true, tags: ["protein_rich"] },
{ name: "Chicken Stew", category: "south indian", caloriesPer100g: 180, sugar_g: 2.0, fat_g: 9.0, protein_g: 14.0, processed: false, tags: [] },
{ name: "Idiyappam Stew", category: "south indian", caloriesPer100g: 160, sugar_g: 2.5, fat_g: 5.0, protein_g: 4.0, processed: false, tags: [] },
{ name: "Egg Roast Kerala", category: "south indian", caloriesPer100g: 185, sugar_g: 2.5, fat_g: 9.0, protein_g: 10.0, processed: false, tags: [] },
{ name: "Prawn Masala", category: "seafood", caloriesPer100g: 210, sugar_g: 1.0, fat_g: 11.0, protein_g: 19.0, processed: false, tags: ["protein_rich"] },
{ name: "Fish Moilee", category: "seafood", caloriesPer100g: 200, sugar_g: 1.5, fat_g: 10.0, protein_g: 15.0, processed: false, tags: [] },
{ name: "Kappa Meen Curry", category: "south indian", caloriesPer100g: 170, sugar_g: 2.0, fat_g: 7.0, protein_g: 7.0, processed: false, tags: [] },

// More breakfast & tiffin
{ name: "Sabudana Vada", category: "snack", caloriesPer100g: 280, sugar_g: 3.0, fat_g: 15.0, protein_g: 3.0, processed: true, tags: ["fried"] },
{ name: "Onion Pakoda", category: "snack", caloriesPer100g: 330, sugar_g: 3.0, fat_g: 20.0, protein_g: 6.0, processed: true, tags: ["fried"] },
{ name: "Mirchi Bajji", category: "snack", caloriesPer100g: 320, sugar_g: 3.0, fat_g: 18.0, protein_g: 4.0, processed: true, tags: ["fried"] },
{ name: "Bread Omelette", category: "breakfast", caloriesPer100g: 220, sugar_g: 2.0, fat_g: 9.0, protein_g: 11.0, processed: true, tags: [] },
{ name: "Paneer Sandwich Indian", category: "snack", caloriesPer100g: 235, sugar_g: 3.5, fat_g: 9.0, protein_g: 9.0, processed: true, tags: [] },
{ name: "Veg Sandwich Indian", category: "snack", caloriesPer100g: 200, sugar_g: 3.0, fat_g: 8.0, protein_g: 6.0, processed: true, tags: [] },
{ name: "Bombay Sandwich", category: "snack", caloriesPer100g: 220, sugar_g: 3.5, fat_g: 9.0, protein_g: 7.0, processed: true, tags: [] },
{ name: "Egg Bhurji Pav", category: "snack", caloriesPer100g: 240, sugar_g: 3.0, fat_g: 10.0, protein_g: 10.0, processed: true, tags: [] },
{ name: "Paneer Bhurji Pav", category: "snack", caloriesPer100g: 245, sugar_g: 3.0, fat_g: 11.0, protein_g: 10.0, processed: true, tags: [] },
{ name: "Anda Paratha", category: "breakfast", caloriesPer100g: 230, sugar_g: 2.0, fat_g: 9.0, protein_g: 9.0, processed: true, tags: [] },

// Simple veg items often eaten with roti
{ name: "Plain Tadka Dal", category: "north indian", caloriesPer100g: 160, sugar_g: 2.0, fat_g: 7.0, protein_g: 7.0, processed: false, tags: [] },
{ name: "Tur Dal Fry", category: "north indian", caloriesPer100g: 170, sugar_g: 2.3, fat_g: 7.5, protein_g: 7.5, processed: false, tags: [] },
{ name: "Moong Dal Fry", category: "north indian", caloriesPer100g: 160, sugar_g: 2.0, fat_g: 6.0, protein_g: 8.0, processed: false, tags: [] },
{ name: "Lauki Sabzi", category: "north indian", caloriesPer100g: 70, sugar_g: 2.0, fat_g: 3.0, protein_g: 2.0, processed: false, tags: [] },
{ name: "Tinda Sabzi", category: "north indian", caloriesPer100g: 80, sugar_g: 2.0, fat_g: 3.0, protein_g: 2.0, processed: false, tags: [] },
{ name: "Aloo Tamatar", category: "north indian", caloriesPer100g: 130, sugar_g: 3.0, fat_g: 6.0, protein_g: 2.0, processed: false, tags: [] },

// A few Indian-style salads / healthy sides
{ name: "Kachumber Salad", category: "healthy", caloriesPer100g: 40, sugar_g: 3.0, fat_g: 1.0, protein_g: 1.0, processed: false, tags: [] },
{ name: "Sprouts Salad Indian", category: "healthy", caloriesPer100g: 55, sugar_g: 3.0, fat_g: 0.8, protein_g: 6.0, processed: false, tags: ["protein_rich"] },
{ name: "Cabbage Carrot Salad", category: "healthy", caloriesPer100g: 35, sugar_g: 3.0, fat_g: 0.6, protein_g: 1.2, processed: false, tags: [] },
{ name: "Curd Raita", category: "dairy", caloriesPer100g: 55, sugar_g: 3.0, fat_g: 2.0, protein_g: 3.0, processed: false, tags: [] },
{ name: "Boondi Raita", category: "dairy", caloriesPer100g: 95, sugar_g: 3.0, fat_g: 6.0, protein_g: 3.0, processed: true, tags: [] },

// Some fruits commonly eaten in India (helps coverage)
{ name: "Mango", category: "fruit", caloriesPer100g: 60, sugar_g: 13.7, fat_g: 0.4, protein_g: 0.8, processed: false, tags: ["fruit"] },
{ name: "Banana", category: "fruit", caloriesPer100g: 89, sugar_g: 12.2, fat_g: 0.3, protein_g: 1.1, processed: false, tags: ["fruit"] },
{ name: "Apple", category: "fruit", caloriesPer100g: 52, sugar_g: 10.4, fat_g: 0.2, protein_g: 0.3, processed: false, tags: ["fruit"] },
{ name: "Orange", category: "fruit", caloriesPer100g: 47, sugar_g: 9.4, fat_g: 0.1, protein_g: 0.9, processed: false, tags: ["fruit"] },
{ name: "Guava", category: "fruit", caloriesPer100g: 68, sugar_g: 8.9, fat_g: 1.0, protein_g: 2.6, processed: false, tags: ["fruit"] },
{ name: "Papaya", category: "fruit", caloriesPer100g: 43, sugar_g: 8.0, fat_g: 0.3, protein_g: 0.5, processed: false, tags: ["fruit"] },
{ name: "Pomegranate", category: "fruit", caloriesPer100g: 72, sugar_g: 14.0, fat_g: 1.0, protein_g: 1.0, processed: false, tags: ["fruit"] },
{ name: "Watermelon", category: "fruit", caloriesPer100g: 30, sugar_g: 6.2, fat_g: 0.2, protein_g: 0.6, processed: false, tags: ["fruit"] },
{ name: "Mosambi", category: "fruit", caloriesPer100g: 43, sugar_g: 8.0, fat_g: 0.2, protein_g: 0.8, processed: false, tags: ["fruit"] },
{ name: "Custard Apple", category: "fruit", caloriesPer100g: 94, sugar_g: 18.0, fat_g: 0.3, protein_g: 2.1, processed: false, tags: ["fruit"] },
// ---- PART 3: Foods 501–900 ----

// Fruits
{ name: "Apple", category: "fruit", caloriesPer100g: 52, sugar_g: 10.4, fat_g: 0.2, protein_g: 0.3, processed: false, tags: ["fruit"] },
{ name: "Banana", category: "fruit", caloriesPer100g: 96, sugar_g: 12.2, fat_g: 0.3, protein_g: 1.2, processed: false, tags: ["fruit"] },
{ name: "Orange", category: "fruit", caloriesPer100g: 47, sugar_g: 9.0, fat_g: 0.1, protein_g: 0.9, processed: false, tags: ["fruit"] },
{ name: "Mango", category: "fruit", caloriesPer100g: 60, sugar_g: 14.0, fat_g: 0.4, protein_g: 0.8, processed: false, tags: ["fruit"] },
{ name: "Strawberry", category: "fruit", caloriesPer100g: 33, sugar_g: 4.9, fat_g: 0.3, protein_g: 0.7, processed: false, tags: ["fruit"] },
{ name: "Watermelon", category: "fruit", caloriesPer100g: 30, sugar_g: 6.0, fat_g: 0.2, protein_g: 0.6, processed: false, tags: ["fruit"] },
{ name: "Pineapple", category: "fruit", caloriesPer100g: 50, sugar_g: 10.0, fat_g: 0.1, protein_g: 0.5, processed: false, tags: ["fruit"] },
{ name: "Papaya", category: "fruit", caloriesPer100g: 43, sugar_g: 7.8, fat_g: 0.3, protein_g: 0.5, processed: false, tags: ["fruit"] },
{ name: "Kiwi", category: "fruit", caloriesPer100g: 61, sugar_g: 9.0, fat_g: 0.5, protein_g: 1.1, processed: false, tags: ["fruit"] },
{ name: "Grapes", category: "fruit", caloriesPer100g: 69, sugar_g: 15.0, fat_g: 0.2, protein_g: 0.6, processed: false, tags: ["fruit"] },

// Vegetables
{ name: "Tomato", category: "vegetable", caloriesPer100g: 18, sugar_g: 2.7, fat_g: 0.2, protein_g: 0.9, processed: false, tags: [] },
{ name: "Carrot", category: "vegetable", caloriesPer100g: 41, sugar_g: 4.7, fat_g: 0.2, protein_g: 0.9, processed: false, tags: [] },
{ name: "Broccoli", category: "vegetable", caloriesPer100g: 34, sugar_g: 1.7, fat_g: 0.4, protein_g: 2.8, processed: false, tags: ["healthy"] },
{ name: "Spinach", category: "vegetable", caloriesPer100g: 23, sugar_g: 0.4, fat_g: 0.4, protein_g: 2.9, processed: false, tags: ["healthy"] },
{ name: "Cucumber", category: "vegetable", caloriesPer100g: 16, sugar_g: 1.7, fat_g: 0.1, protein_g: 0.7, processed: false, tags: [] },
{ name: "Paneer Salad", category: "healthy", caloriesPer100g: 180, sugar_g: 3.0, fat_g: 10.0, protein_g: 12.0, processed: false, tags: ["protein_rich"] },
{ name: "Green Salad", category: "healthy", caloriesPer100g: 40, sugar_g: 2.0, fat_g: 1.0, protein_g: 2.0, processed: false, tags: [] },
{ name: "Avocado Salad", category: "healthy", caloriesPer100g: 160, sugar_g: 1.5, fat_g: 14.0, protein_g: 2.5, processed: false, tags: [] },
{ name: "Boiled Corn", category: "vegetable", caloriesPer100g: 86, sugar_g: 6.3, fat_g: 1.2, protein_g: 3.4, processed: false, tags: [] },
{ name: "Beetroot Salad", category: "healthy", caloriesPer100g: 50, sugar_g: 6.8, fat_g: 0.2, protein_g: 1.6, processed: false, tags: [] },

// Indian Snacks
{ name: "Murukku", category: "snack", caloriesPer100g: 470, sugar_g: 2.0, fat_g: 24.0, protein_g: 6.0, processed: true, tags: ["fried"] },
{ name: "Sev", category: "snack", caloriesPer100g: 550, sugar_g: 3.0, fat_g: 36.0, protein_g: 9.0, processed: true, tags: ["fried"] },
{ name: "Mixture", category: "snack", caloriesPer100g: 530, sugar_g: 3.0, fat_g: 34.0, protein_g: 9.0, processed: true, tags: ["fried"] },
{ name: "Banana Chips", category: "snack", caloriesPer100g: 520, sugar_g: 2.0, fat_g: 34.0, protein_g: 2.3, processed: true, tags: ["junk"] },
{ name: "Aloo Bhujia", category: "snack", caloriesPer100g: 550, sugar_g: 2.0, fat_g: 35.0, protein_g: 7.0, processed: true, tags: ["junk"] },
{ name: "Paneer Pakoda", category: "snack", caloriesPer100g: 295, sugar_g: 1.5, fat_g: 19.0, protein_g: 10.0, processed: true, tags: ["fried"] },
{ name: "Chicken 65", category: "south indian", caloriesPer100g: 280, sugar_g: 2.0, fat_g: 15.0, protein_g: 20.0, processed: true, tags: ["fried", "protein_rich"] },
{ name: "Chilli Paneer", category: "snack", caloriesPer100g: 245, sugar_g: 3.0, fat_g: 14.0, protein_g: 10.0, processed: true, tags: [] },
{ name: "Chilli Chicken", category: "snack", caloriesPer100g: 260, sugar_g: 3.0, fat_g: 12.0, protein_g: 18.0, processed: true, tags: ["protein_rich"] },
{ name: "Veg Momos", category: "snack", caloriesPer100g: 180, sugar_g: 2.0, fat_g: 4.0, protein_g: 5.0, processed: true, tags: [] },

// Fast Food & Restaurant
{ name: "Pizza Margherita", category: "fast food", caloriesPer100g: 260, sugar_g: 3.0, fat_g: 10.0, protein_g: 11.0, processed: true, tags: ["junk"] },
{ name: "Cheese Burger", category: "fast food", caloriesPer100g: 295, sugar_g: 5.0, fat_g: 15.0, protein_g: 17.0, processed: true, tags: ["junk"] },
{ name: "French Fries", category: "fast food", caloriesPer100g: 312, sugar_g: 0.7, fat_g: 15.0, protein_g: 3.4, processed: true, tags: ["fried"] },
{ name: "Chicken Nuggets", category: "fast food", caloriesPer100g: 290, sugar_g: 1.0, fat_g: 18.0, protein_g: 16.0, processed: true, tags: [] },
{ name: "Hot Dog", category: "fast food", caloriesPer100g: 290, sugar_g: 3.9, fat_g: 16.0, protein_g: 10.0, processed: true, tags: [] },
{ name: "Sub Sandwich", category: "fast food", caloriesPer100g: 230, sugar_g: 3.0, fat_g: 8.0, protein_g: 15.0, processed: true, tags: [] },
{ name: "Chicken Wrap", category: "fast food", caloriesPer100g: 220, sugar_g: 2.0, fat_g: 10.0, protein_g: 15.0, processed: true, tags: [] },
{ name: "Garlic Bread", category: "fast food", caloriesPer100g: 350, sugar_g: 2.2, fat_g: 18.0, protein_g: 9.0, processed: true, tags: ["junk"] },
{ name: "Onion Rings", category: "fast food", caloriesPer100g: 350, sugar_g: 3.0, fat_g: 21.0, protein_g: 4.0, processed: true, tags: ["fried"] },
{ name: "Fried Rice Chinese Style", category: "asian", caloriesPer100g: 180, sugar_g: 1.2, fat_g: 7.0, protein_g: 4.0, processed: true, tags: [] },

// More International Foods
{ name: "Sushi Roll", category: "japanese", caloriesPer100g: 145, sugar_g: 2.0, fat_g: 4.0, protein_g: 8.0, processed: true, tags: ["protein_rich"] },
{ name: "Ramen Noodles", category: "japanese", caloriesPer100g: 190, sugar_g: 2.2, fat_g: 6.0, protein_g: 6.0, processed: true, tags: [] },
{ name: "Kimchi", category: "korean", caloriesPer100g: 35, sugar_g: 1.5, fat_g: 0.5, protein_g: 2.4, processed: true, tags: ["healthy"] },
{ name: "Tacos Chicken", category: "mexican", caloriesPer100g: 210, sugar_g: 2.0, fat_g: 11.0, protein_g: 14.0, processed: true, tags: [] },
{ name: "Nachos with Cheese", category: "mexican", caloriesPer100g: 310, sugar_g: 2.5, fat_g: 18.0, protein_g: 6.0, processed: true, tags: ["junk"] },
{ name: "Spaghetti Bolognese", category: "italian", caloriesPer100g: 255, sugar_g: 2.5, fat_g: 12.0, protein_g: 11.0, processed: true, tags: [] },
{ name: "Lasagna", category: "italian", caloriesPer100g: 280, sugar_g: 3.0, fat_g: 17.0, protein_g: 12.0, processed: true, tags: [] },
{ name: "Falafel Wrap", category: "mediterranean", caloriesPer100g: 230, sugar_g: 2.0, fat_g: 10.0, protein_g: 9.0, processed: true, tags: [] },
{ name: "Shawarma", category: "mediterranean", caloriesPer100g: 265, sugar_g: 2.2, fat_g: 14.0, protein_g: 17.0, processed: true, tags: [] },
{ name: "Caesar Salad", category: "salad", caloriesPer100g: 180, sugar_g: 1.3, fat_g: 12.0, protein_g: 7.0, processed: false, tags: ["healthy"] },

// Proteins
{ name: "Boiled Egg", category: "protein", caloriesPer100g: 155, sugar_g: 1.1, fat_g: 11.0, protein_g: 13.0, processed: false, tags: ["protein_rich"] },
{ name: "Scrambled Eggs", category: "protein", caloriesPer100g: 148, sugar_g: 1.0, fat_g: 10.0, protein_g: 10.0, processed: true, tags: [] },
{ name: "Grilled Chicken", category: "protein", caloriesPer100g: 165, sugar_g: 0, fat_g: 3.6, protein_g: 31.0, processed: false, tags: ["protein_rich"] },
{ name: "Roasted Chicken", category: "protein", caloriesPer100g: 180, sugar_g: 0.5, fat_g: 8.0, protein_g: 25.0, processed: false, tags: ["protein_rich"] },
{ name: "Fish Fry", category: "seafood", caloriesPer100g: 200, sugar_g: 0.5, fat_g: 9.0, protein_g: 22.0, processed: true, tags: ["fried"] },
{ name: "Prawn Masala", category: "seafood", caloriesPer100g: 185, sugar_g: 1.0, fat_g: 8.0, protein_g: 20.0, processed: false, tags: ["protein_rich"] },
{ name: "Mutton Curry", category: "protein", caloriesBePer100g: 295, sugar_g: 3.0, fat_g: 18.0, protein_g: 15.0, processed: true, tags: [] },
{ name: "Turkey Breast", category: "protein", caloriesPer100g: 135, sugar_g: 0, fat_g: 1.5, protein_g: 29.0, processed: false, tags: ["protein_rich"] },
{ name: "Paneer Tikka", category: "protein", caloriesPer100g: 190, sugar_g: 1.2, fat_g: 10.0, protein_g: 15.0, processed: false, tags: ["protein_rich"] },
{ name: "Tofu Stir Fry", category: "protein", caloriesPer100g: 132, sugar_g: 2.0, fat_g: 7.0, protein_g: 10.0, processed: false, tags: ["healthy"] },

// Healthy Extras
{ name: "Protein Shake", category: "drink", caloriesPer100g: 120, sugar_g: 3.0, fat_g: 2.0, protein_g: 22.0, processed: true, tags: ["protein_rich"] },
{ name: "Granola Bar", category: "snack", caloriesPer100g: 471, sugar_g: 20.0, fat_g: 19.0, protein_g: 10.0, processed: true, tags: [] },
{ name: "Mixed Nuts", category: "snack", caloriesPer100g: 607, sugar_g: 4.5, fat_g: 54.0, protein_g: 20.0, processed: false, tags: ["protein_rich"] },
{ name: "Oatmeal", category: "breakfast", caloriesPer100g: 68, sugar_g: 0.5, fat_g: 1.4, protein_g: 2.4, processed: false, tags: ["healthy"] },
{ name: "Greek Yogurt", category: "dairy", caloriesPer100g: 59, sugar_g: 3.6, fat_g: 0.4, protein_g: 10.0, processed: false, tags: ["protein_rich"] },
{ name: "Ragi Porridge", category: "healthy", caloriesPer100g: 130, sugar_g: 6.0, fat_g: 3.0, protein_g: 4.0, processed: false, tags: [] },
{ name: "Sprouts Salad", category: "healthy", caloriesPer100g: 45, sugar_g: 2.5, fat_g: 0.5, protein_g: 5.5, processed: false, tags: ["protein_rich"] },
{ name: "Boiled Sweet Potato", category: "healthy", caloriesPer100g: 86, sugar_g: 4.2, fat_g: 0.1, protein_g: 1.6, processed: false, tags: [] },
{ name: "Fruit Bowl", category: "healthy", caloriesPer100g: 70, sugar_g: 12.0, fat_g: 0.3, protein_g: 0.8, processed: false, tags: [] },
{ name: "Cauliflower Rice", category: "healthy", caloriesPer100g: 25, sugar_g: 1.9, fat_g: 0.3, protein_g: 2.4, processed: false, tags: [] },
// ---- PART 3 Continued: Foods 651–850 ----

// More Healthy Foods
{ name: "Chia Pudding", category: "healthy", caloriesPer100g: 120, sugar_g: 5.0, fat_g: 4.0, protein_g: 4.0, processed: false, tags: ["healthy"] },
{ name: "Quinoa Bowl", category: "healthy", caloriesPer100g: 135, sugar_g: 3.0, fat_g: 4.0, protein_g: 5.0, processed: false, tags: ["healthy"] },
{ name: "Green Smoothie", category: "drink", caloriesPer100g: 60, sugar_g: 10.0, fat_g: 0.5, protein_g: 1.8, processed: false, tags: ["healthy"] },
{ name: "Mushroom Soup", category: "soup", caloriesPer100g: 50, sugar_g: 1.5, fat_g: 2.0, protein_g: 3.0, processed: false, tags: [] },
{ name: "Tomato Soup", category: "soup", caloriesPer100g: 40, sugar_g: 4.8, fat_g: 1.0, protein_g: 1.8, processed: true, tags: [] },
{ name: "Pumpkin Soup", category: "soup", caloriesPer100g: 38, sugar_g: 4.7, fat_g: 0.7, protein_g: 1.0, processed: false, tags: [] },
{ name: "Sweet Corn Soup", category: "soup", caloriesPer100g: 52, sugar_g: 4.5, fat_g: 1.5, protein_g: 2.2, processed: true, tags: [] },
{ name: "Veg Clear Soup", category: "soup", caloriesPer100g: 30, sugar_g: 2.0, fat_g: 0.3, protein_g: 1.0, processed: false, tags: [] },
{ name: "Chicken Clear Soup", category: "soup", caloriesPer100g: 50, sugar_g: 1.5, fat_g: 2.0, protein_g: 7.0, processed: false, tags: ["protein_rich"] },
{ name: "Miso Soup", category: "japanese", caloriesPer100g: 36, sugar_g: 2.0, fat_g: 1.0, protein_g: 3.0, processed: true, tags: [] },

// International Street Food
{ name: "Korean Fried Chicken", category: "korean", caloriesPer100g: 300, sugar_g: 4.0, fat_g: 18.0, protein_g: 22.0, processed: true, tags: ["fried"] },
{ name: "Kimbap", category: "korean", caloriesPer100g: 150, sugar_g: 2.0, fat_g: 4.0, protein_g: 8.0, processed: true, tags: [] },
{ name: "Pho Soup", category: "vietnamese", caloriesPer100g: 45, sugar_g: 1.5, fat_g: 1.0, protein_g: 4.0, processed: false, tags: ["healthy"] },
{ name: "Spring Rolls", category: "vietnamese", caloriesPer100g: 200, sugar_g: 3.0, fat_g: 10.0, protein_g: 6.0, processed: true, tags: [] },
{ name: "Pad Thai", category: "thai", caloriesPer100g: 230, sugar_g: 4.0, fat_g: 10.0, protein_g: 8.0, processed: true, tags: [] },
{ name: "Thai Green Curry", category: "thai", caloriesPer100g: 190, sugar_g: 2.0, fat_g: 12.0, protein_g: 6.0, processed: true, tags: [] },
{ name: "Dim Sum", category: "chinese", caloriesPer100g: 180, sugar_g: 2.5, fat_g: 6.0, protein_g: 6.5, processed: true, tags: [] },
{ name: "Kung Pao Chicken", category: "chinese", caloriesPer100g: 240, sugar_g: 6.0, fat_g: 13.0, protein_g: 18.0, processed: true, tags: ["protein_rich"] },
{ name: "Chow Mein", category: "chinese", caloriesPer100g: 205, sugar_g: 2.0, fat_g: 9.0, protein_g: 7.0, processed: true, tags: [] },
{ name: "Hakka Noodles", category: "asian", caloriesPer100g: 200, sugar_g: 2.5, fat_g: 7.0, protein_g: 5.0, processed: true, tags: [] },

// Beverages
{ name: "Orange Juice", category: "drink", caloriesPer100g: 45, sugar_g: 9.0, fat_g: 0.2, protein_g: 0.7, processed: true, tags: [] },
{ name: "Lemon Juice", category: "drink", caloriesPer100g: 18, sugar_g: 1.5, fat_g: 0.1, protein_g: 0.3, processed: false, tags: [] },
{ name: "Coca Cola", category: "drink", caloriesPer100g: 44, sugar_g: 11.0, fat_g: 0, protein_g: 0, processed: true, tags: ["high_sugar"] },
{ name: "Sprite", category: "drink", caloriesPer100g: 39, sugar_g: 10.0, fat_g: 0, protein_g: 0, processed: true, tags: ["high_sugar"] },
{ name: "Pepsi", category: "drink", caloriesPer100g: 42, sugar_g: 11.0, fat_g: 0, protein_g: 0, processed: true, tags: ["high_sugar"] },
{ name: "Iced Tea", category: "drink", caloriesPer100g: 28, sugar_g: 7.0, fat_g: 0, protein_g: 0, processed: true, tags: [] },
{ name: "Cold Coffee", category: "drink", caloriesPer100g: 95, sugar_g: 15.0, fat_g: 2.0, protein_g: 1.0, processed: true, tags: [] },
{ name: "Smoothie Bowl", category: "healthy", caloriesPer100g: 120, sugar_g: 15.0, fat_g: 2.0, protein_g: 2.5, processed: false, tags: [] },
{ name: "Black Tea", category: "drink", caloriesPer100g: 1, sugar_g: 0, fat_g: 0, protein_g: 0, processed: false, tags: ["healthy"] },
{ name: "Sugarcane Juice", category: "drink", caloriesPer100g: 45, sugar_g: 12.0, fat_g: 0, protein_g: 0, processed: true, tags: ["high_sugar"] },

// Bakery & Desserts International
{ name: "Chocolate Cake", category: "dessert", caloriesPer100g: 410, sugar_g: 35.0, fat_g: 20.0, protein_g: 5.0, processed: true, tags: ["dessert"] },
{ name: "Doughnut", category: "dessert", caloriesPer100g: 452, sugar_g: 25.0, fat_g: 25.0, protein_g: 5.0, processed: true, tags: ["dessert"] },
{ name: "Brownie", category: "dessert", caloriesPer100g: 466, sugar_g: 31.0, fat_g: 26.0, protein_g: 4.5, processed: true, tags: ["dessert"] },
{ name: "Cupcake", category: "dessert", caloriesPer100g: 380, sugar_g: 32.0, fat_g: 17.0, protein_g: 4.0, processed: true, tags: [] },
{ name: "Muffin", category: "dessert", caloriesPer100g: 350, sugar_g: 30.0, fat_g: 15.0, protein_g: 4.0, processed: true, tags: [] },
{ name: "Croissant", category: "bakery", caloriesPer100g: 406, sugar_g: 5.0, fat_g: 21.0, protein_g: 8.0, processed: true, tags: [] },
{ name: "Macaron", category: "dessert", caloriesPer100g: 350, sugar_g: 38.0, fat_g: 14.0, protein_g: 4.0, processed: true, tags: [] },
{ name: "Cheesecake", category: "dessert", caloriesPer100g: 321, sugar_g: 25.0, fat_g: 22.0, protein_g: 6.0, processed: true, tags: ["high_fat"] },
{ name: "Ice Cream Sundae", category: "dessert", caloriesPer100g: 242, sugar_g: 20.0, fat_g: 12.0, protein_g: 4.0, processed: true, tags: ["dessert"] },
{ name: "Pancakes", category: "western", caloriesPer100g: 227, sugar_g: 9.0, fat_g: 10.0, protein_g: 6.0, processed: true, tags: [] },

// Western Meals
{ name: "Grilled Sandwich", category: "fast food", caloriesPer100g: 240, sugar_g: 3.0, fat_g: 10.0, protein_g: 12.0, processed: true, tags: [] },
{ name: "Fish and Chips", category: "western", caloriesPer100g: 330, sugar_g: 0.5, fat_g: 18.0, protein_g: 19.0, processed: true, tags: ["fried"] },
{ name: "Steak", category: "western", caloriesPer100g: 271, sugar_g: 0, fat_g: 19.0, protein_g: 25.0, processed: false, tags: ["protein_rich"] },
{ name: "Caesar Wrap", category: "fast food", caloriesPer100g: 230, sugar_g: 2.0, fat_g: 10.0, protein_g: 12.0, processed: true, tags: [] },
{ name: "Mashed Potatoes", category: "western", caloriesPer100g: 88, sugar_g: 1.0, fat_g: 3.4, protein_g: 1.7, processed: false, tags: [] },
{ name: "Garlic Mashed Potato", category: "western", caloriesPer100g: 100, sugar_g: 1.5, fat_g: 5.0, protein_g: 2.0, processed: true, tags: [] },
{ name: "Beef Burger", category: "fast food", caloriesPer100g: 295, sugar_g: 5.0, fat_g: 15.0, protein_g: 17.0, processed: true, tags: [] },
{ name: "Chicken Pizza", category: "fast food", caloriesPer100g: 270, sugar_g: 4.0, fat_g: 12.0, protein_g: 14.0, processed: true, tags: [] },
{ name: "Veggie Pizza", category: "fast food", caloriesPer100g: 245, sugar_g: 4.0, fat_g: 10.0, protein_g: 10.0, processed: true, tags: [] },
{ name: "BBQ Pizza", category: "fast food", caloriesPer100g: 280, sugar_g: 7.0, fat_g: 12.0, protein_g: 14.0, processed: true, tags: ["junk"] },

// Ending part for this chunk
{ name: "Avocado Toast", category: "western", caloriesPer100g: 160, sugar_g: 2.0, fat_g: 8.0, protein_g: 4.0, processed: false, tags: ["healthy"] },
{ name: "Veggie Burger", category: "fast food", caloriesPer100g: 235, sugar_g: 5.0, fat_g: 8.0, protein_g: 12.0, processed: true, tags: [] },
{ name: "Shrimp Cocktail", category: "seafood", caloriesPer100g: 105, sugar_g: 2.0, fat_g: 1.5, protein_g: 20.0, processed: true, tags: ["protein_rich"] },
{ name: "Stuffed Mushrooms", category: "western", caloriesPer100g: 150, sugar_g: 3.0, fat_g: 9.0, protein_g: 6.0, processed: true, tags: [] },
{ name: "Burrito Bowl", category: "mexican", caloriesPer100g: 210, sugar_g: 2.5, fat_g: 10.0, protein_g: 14.0, processed: true, tags: [] },

// —— PART 3 Final: Foods 851–1050 ——

// More Western / Continental
{ name: "Beef Steak Bowl", category: "western", caloriesPer100g: 260, sugar_g: 1.0, fat_g: 15.0, protein_g: 26.0, processed: false, tags: ["protein_rich"] },
{ name: "Chicken Caesar Salad", category: "salad", caloriesPer100g: 180, sugar_g: 1.5, fat_g: 10.0, protein_g: 12.0, processed: false, tags: ["healthy"] },
{ name: "Baked Potato", category: "western", caloriesPer100g: 93, sugar_g: 1.7, fat_g: 0.1, protein_g: 2.5, processed: false, tags: [] },
{ name: "Veggie Wrap", category: "fast food", caloriesPer100g: 200, sugar_g: 2.0, fat_g: 7.0, protein_g: 6.0, processed: true, tags: [] },
{ name: "Chicken Burrito", category: "mexican", caloriesPer100g: 250, sugar_g: 3.0, fat_g: 11.0, protein_g: 14.0, processed: true, tags: [] },
{ name: "Fish Burrito", category: "mexican", caloriesPer100g: 240, sugar_g: 2.8, fat_g: 10.0, protein_g: 15.0, processed: true, tags: [] },
{ name: "Fried Fish Burger", category: "fast food", caloriesPer100g: 310, sugar_g: 4.0, fat_g: 17.0, protein_g: 15.0, processed: true, tags: ["fried"] },
{ name: "Veggie Lasagna", category: "italian", caloriesPer100g: 250, sugar_g: 5.0, fat_g: 12.0, protein_g: 9.0, processed: true, tags: [] },
{ name: "BBQ Chicken Wings", category: "western", caloriesPer100g: 280, sugar_g: 4.5, fat_g: 17.0, protein_g: 21.0, processed: true, tags: [] },
{ name: "Garlic Chicken Pasta", category: "italian", caloriesPer100g: 260, sugar_g: 3.0, fat_g: 12.0, protein_g: 15.0, processed: true, tags: [] },

// More Breakfast Foods
{ name: "Oats with Milk", category: "breakfast", caloriesPer100g: 68, sugar_g: 6.0, fat_g: 2.0, protein_g: 3.0, processed: false, tags: ["healthy"] },
{ name: "Boiled Egg Whites", category: "protein", caloriesPer100g: 52, sugar_g: 1.0, fat_g: 1.0, protein_g: 11.0, processed: false, tags: ["protein_rich"] },
{ name: "Upma Veg", category: "south indian", caloriesPer100g: 140, sugar_g: 2.0, fat_g: 5.0, protein_g: 3.0, processed: false, tags: [] },
{ name: "Omelette Classic", category: "breakfast", caloriesPer100g: 150, sugar_g: 1.0, fat_g: 12.0, protein_g: 10.0, processed: true, tags: [] },
{ name: "Breakfast Burrito Veg", category: "mexican", caloriesPer100g: 220, sugar_g: 3.0, fat_g: 10.0, protein_g: 9.0, processed: true, tags: [] },
{ name: "Paneer Sandwich", category: "snack", caloriesPer100g: 240, sugar_g: 3.0, fat_g: 9.0, protein_g: 13.0, processed: true, tags: ["protein_rich"] },
{ name: "Chicken Sandwich", category: "snack", caloriesPer100g: 250, sugar_g: 3.0, fat_g: 7.0, protein_g: 17.0, processed: true, tags: [] },
{ name: "Egg Sandwich", category: "snack", caloriesPer100g: 230, sugar_g: 2.0, fat_g: 8.0, protein_g: 14.0, processed: true, tags: [] },
{ name: "Bagel with Cream Cheese", category: "breakfast", caloriesPer100g: 260, sugar_g: 5.0, fat_g: 11.0, protein_g: 9.0, processed: true, tags: [] },
{ name: "Banana Smoothie", category: "drink", caloriesPer100g: 90, sugar_g: 15.0, fat_g: 0.5, protein_g: 2.0, processed: true, tags: [] },

// Middle Eastern
{ name: "Hummus", category: "mediterranean", caloriesPer100g: 160, sugar_g: 0.3, fat_g: 9.6, protein_g: 8.0, processed: false, tags: ["protein_rich"] },
{ name: "Pita Bread", category: "bread", caloriesPer100g: 275, sugar_g: 1.0, fat_g: 1.0, protein_g: 8.0, processed: false, tags: [] },
{ name: "Baba Ganoush", category: "mediterranean", caloriesPer100g: 120, sugar_g: 2.0, fat_g: 8.0, protein_g: 2.0, processed: false, tags: ["healthy"] },
{ name: "Fattoush Salad", category: "healthy", caloriesPer100g: 70, sugar_g: 2.0, fat_g: 3.0, protein_g: 2.0, processed: false, tags: [] },
{ name: "Kofta Kabab", category: "protein", caloriesPer100g: 260, sugar_g: 1.5, fat_g: 15.0, protein_g: 24.0, processed: true, tags: ["protein_rich"] },
{ name: "Shish Tawook", category: "mediterranean", caloriesPer100g: 135, sugar_g: 1.0, fat_g: 4.0, protein_g: 27.0, processed: false, tags: ["protein_rich"] },
{ name: "Lebanese Rice", category: "rice", caloriesPer100g: 180, sugar_g: 1.5, fat_g: 6.0, protein_g: 4.0, processed: true, tags: [] },
{ name: "Manakeesh", category: "middle eastern", caloriesPer100g: 310, sugar_g: 3.0, fat_g: 15.0, protein_g: 12.0, processed: true, tags: [] },
{ name: "Baklava", category: "dessert", caloriesPer100g: 430, sugar_g: 30.0, fat_g: 22.0, protein_g: 5.0, processed: true, tags: ["dessert"] },
{ name: "Falafel Bowl", category: "mediterranean", caloriesPer100g: 225, sugar_g: 2.0, fat_g: 12.0, protein_g: 9.0, processed: true, tags: [] },

// Drinks & Milkshakes
{ name: "Chocolate Milkshake", category: "drink", caloriesPer100g: 150, sugar_g: 25.0, fat_g: 3.0, protein_g: 3.5, processed: true, tags: ["high_sugar"] },
{ name: "Strawberry Milkshake", category: "drink", caloriesPer100g: 150, sugar_g: 26.0, fat_g: 3.0, protein_g: 3.0, processed: true, tags: ["high_sugar"] },
{ name: "Mango Milkshake", category: "drink", caloriesPer100g: 160, sugar_g: 28.0, fat_g: 3.0, protein_g: 3.0, processed: true, tags: ["high_sugar"] },
{ name: "Vanilla Milkshake", category: "drink", caloriesPer100g: 155, sugar_g: 24.0, fat_g: 3.0, protein_g: 3.2, processed: true, tags: [] },
{ name: "Black Coffee", category: "drink", caloriesPer100g: 1, sugar_g: 0, fat_g: 0, protein_g: 0, processed: false, tags: ["healthy"] },
{ name: "Badam Shake", category: "drink", caloriesPer100g: 180, sugar_g: 20.0, fat_g: 7.0, protein_g: 5.0, processed: true, tags: [] },
{ name: "Protein Coffee", category: "drink", caloriesPer100g: 70, sugar_g: 3.0, fat_g: 1.0, protein_g: 10.0, processed: true, tags: ["protein_rich"] },
{ name: "Green Tea", category: "drink", caloriesPer100g: 1, sugar_g: 0, fat_g: 0, protein_g: 0, processed: false, tags: ["healthy"] },
{ name: "Hot Chocolate", category: "drink", caloriesPer100g: 70, sugar_g: 12.0, fat_g: 2.0, protein_g: 1.0, processed: true, tags: [] },
{ name: "Frappe Latte", category: "drink", caloriesPer100g: 110, sugar_g: 18.0, fat_g: 3.0, protein_g: 2.0, processed: true, tags: [] },

// More Asian Foods
{ name: "Schezwan Noodles", category: "asian", caloriesPer100g: 210, sugar_g: 2.0, fat_g: 7.0, protein_g: 6.0, processed: true, tags: [] },
{ name: "Chicken Dumplings", category: "asian", caloriesPer100g: 200, sugar_g: 1.0, fat_g: 7.0, protein_g: 14.0, processed: true, tags: [] },
{ name: "Tofu Noodles", category: "asian", caloriesPer100g: 190, sugar_g: 2.2, fat_g: 5.0, protein_g: 8.0, processed: true, tags: ["protein_rich"] },
{ name: "Teriyaki Chicken", category: "japanese", caloriesPer100g: 210, sugar_g: 4.0, fat_g: 9.0, protein_g: 20.0, processed: true, tags: [] },
{ name: "Tempura Shrimp", category: "japanese", caloriesPer100g: 280, sugar_g: 1.0, fat_g: 17.0, protein_g: 13.0, processed: true, tags: ["fried"] },
{ name: "Egg Fried Rice", category: "asian", caloriesPer100g: 168, sugar_g: 1.0, fat_g: 5.0, protein_g: 4.8, processed: true, tags: [] },
{ name: "Kung Pao Tofu", category: "asian", caloriesPer100g: 195, sugar_g: 4.0, fat_g: 10.0, protein_g: 8.0, processed: true, tags: [] },
{ name: "Veg Sushi", category: "japanese", caloriesPer100g: 142, sugar_g: 2.0, fat_g: 3.0, protein_g: 7.0, processed: true, tags: [] },
{ name: "Chicken Pho", category: "vietnamese", caloriesPer100g: 50, sugar_g: 1.0, fat_g: 1.0, protein_g: 6.0, processed: false, tags: ["healthy"] },
{ name: "Sesame Chicken Rice", category: "asian", caloriesPer100g: 220, sugar_g: 3.0, fat_g: 9.0, protein_g: 15.0, processed: true, tags: [] }

// (More items will continue... up to item 1050)
,// —— PART 3 Final End: Foods 1051–1150 ——

// More Asian & Chinese
{ name: "Schezwan Fried Rice", category: "asian", caloriesPer100g: 210, sugar_g: 2.5, fat_g: 7.0, protein_g: 5.0, processed: true, tags: [] },
{ name: "Veg Hakka Noodles", category: "asian", caloriesPer100g: 200, sugar_g: 2.0, fat_g: 6.0, protein_g: 4.0, processed: true, tags: [] },
{ name: "Chicken Hakka Noodles", category: "asian", caloriesPer100g: 215, sugar_g: 2.0, fat_g: 7.0, protein_g: 9.0, processed: true, tags: ["protein_rich"] },
{ name: "Singapore Noodles", category: "asian", caloriesPer100g: 220, sugar_g: 3.0, fat_g: 8.0, protein_g: 6.0, processed: true, tags: [] },
{ name: "Sweet and Sour Chicken", category: "chinese", caloriesPer100g: 230, sugar_g: 7.0, fat_g: 9.0, protein_g: 16.0, processed: true, tags: [] },
{ name: "Crispy Chicken", category: "asian", caloriesPer100g: 275, sugar_g: 3.0, fat_g: 15.0, protein_g: 18.0, processed: true, tags: ["fried"] },
{ name: "Japanese Udon Soup", category: "japanese", caloriesPer100g: 63, sugar_g: 1.0, fat_g: 0.8, protein_g: 2.6, processed: false, tags: ["healthy"] },
{ name: "Tempura Vegetables", category: "asian", caloriesPer100g: 260, sugar_g: 2.0, fat_g: 14.0, protein_g: 4.0, processed: true, tags: ["fried"] },
{ name: "Tandoori Momos", category: "snack", caloriesPer100g: 195, sugar_g: 2.0, fat_g: 7.0, protein_g: 8.0, processed: true, tags: [] },
{ name: "Thai Red Curry", category: "thai", caloriesPer100g: 180, sugar_g: 2.0, fat_g: 10.0, protein_g: 6.0, processed: true, tags: [] },

// Salads & Healthy Bowls
{ name: "Chickpea Salad", category: "healthy", caloriesPer100g: 164, sugar_g: 4.0, fat_g: 8.0, protein_g: 9.0, processed: false, tags: ["protein_rich"] },
{ name: "Fruit Yogurt Bowl", category: "healthy", caloriesPer100g: 105, sugar_g: 14.0, fat_g: 2.0, protein_g: 4.0, processed: false, tags: [] },
{ name: "Tofu Salad", category: "healthy", caloriesPer100g: 90, sugar_g: 1.0, fat_g: 4.5, protein_g: 8.5, processed: false, tags: ["protein_rich"] },
{ name: "Boiled Veg Bowl", category: "healthy", caloriesPer100g: 65, sugar_g: 3.0, fat_g: 0.5, protein_g: 3.0, processed: false, tags: ["healthy"] },
{ name: "Cucumber Lemon Salad", category: "healthy", caloriesPer100g: 25, sugar_g: 2.5, fat_g: 0.1, protein_g: 0.6, processed: false, tags: [] },
{ name: "Egg Avocado Bowl", category: "healthy", caloriesPer100g: 155, sugar_g: 1.0, fat_g: 11.0, protein_g: 11.0, processed: false, tags: ["protein_rich"] },
{ name: "Rajma Salad", category: "healthy", caloriesPer100g: 135, sugar_g: 1.5, fat_g: 5.0, protein_g: 8.0, processed: false, tags: ["protein_rich"] },
{ name: "Lentil Veg Bowl", category: "healthy", caloriesPer100g: 120, sugar_g: 1.0, fat_g: 2.0, protein_g: 9.0, processed: false, tags: ["protein_rich"] },
{ name: "Sprouted Moong Salad", category: "healthy", caloriesPer100g: 44, sugar_g: 1.0, fat_g: 0.2, protein_g: 6.0, processed: false, tags: ["protein_rich"] },
{ name: "Falafel Veg Salad", category: "mediterranean", caloriesPer100g: 200, sugar_g: 2.0, fat_g: 10.0, protein_g: 7.0, processed: true, tags: [] },

// More Indian 🔥
{ name: "Malai Kofta", category: "north indian", caloriesPer100g: 265, sugar_g: 3.0, fat_g: 15.0, protein_g: 8.0, processed: true, tags: [] },
{ name: "Chicken Tikka", category: "north indian", caloriesPer100g: 195, sugar_g: 1.5, fat_g: 9.0, protein_g: 25.0, processed: true, tags: ["protein_rich"] },
{ name: "Veg Cutlet", category: "snack", caloriesPer100g: 240, sugar_g: 2.0, fat_g: 12.0, protein_g: 5.0, processed: true, tags: ["fried"] },
{ name: "Bread Omelette", category: "snack", caloriesPer100g: 220, sugar_g: 3.0, fat_g: 8.0, protein_g: 12.0, processed: true, tags: [] },
{ name: "Kara Kozhambu", category: "south indian", caloriesPer100g: 175, sugar_g: 2.0, fat_g: 10.0, protein_g: 4.0, processed: true, tags: [] },
{ name: "Vegetable Korma", category: "south indian", caloriesPer100g: 170, sugar_g: 2.0, fat_g: 8.0, protein_g: 4.0, processed: true, tags: [] },
{ name: "Masala Vada", category: "snack", caloriesPer100g: 330, sugar_g: 2.5, fat_g: 18.0, protein_g: 10.0, processed: true, tags: ["fried"] },
{ name: "Chicken Roll", category: "snack", caloriesPer100g: 260, sugar_g: 4.0, fat_g: 10.0, protein_g: 15.0, processed: true, tags: [] },
{ name: "Egg Roll", category: "snack", caloriesPer100g: 240, sugar_g: 3.5, fat_g: 9.0, protein_g: 13.0, processed: true, tags: [] },
{ name: "Veg Frankie", category: "snack", caloriesPer100g: 235, sugar_g: 2.0, fat_g: 7.0, protein_g: 6.0, processed: true, tags: [] },

// More Drinks
{ name: "Tender Coconut Water", category: "drink", caloriesPer100g: 19, sugar_g: 3.5, fat_g: 0.2, protein_g: 0.7, processed: false, tags: ["healthy"] },
{ name: "Carrot Juice", category: "drink", caloriesPer100g: 40, sugar_g: 6.0, fat_g: 0.2, protein_g: 1.0, processed: true, tags: [] },
{ name: "Beetroot Juice", category: "drink", caloriesPer100g: 43, sugar_g: 8.0, fat_g: 0.1, protein_g: 1.3, processed: true, tags: [] },
{ name: "Milk", category: "dairy", caloriesPer100g: 42, sugar_g: 5.0, fat_g: 1.0, protein_g: 3.4, processed: false, tags: ["healthy"] },
{ name: "Almond Milk", category: "dairy", caloriesPer100g: 17, sugar_g: 0, fat_g: 1.2, protein_g: 0.5, processed: false, tags: [] },
{ name: "Chocolate Smoothie", category: "drink", caloriesPer100g: 110, sugar_g: 14.0, fat_g: 2.0, protein_g: 2.5, processed: true, tags: [] },
{ name: "Apple Juice", category: "drink", caloriesPer100g: 45, sugar_g: 10.0, fat_g: 0, protein_g: 0, processed: true, tags: [] },
{ name: "Energy Drink", category: "drink", caloriesPer100g: 55, sugar_g: 13.0, fat_g: 0, protein_g: 0, processed: true, tags: ["high_sugar"] },
{ name: "Chilled Coffee", category: "drink", caloriesPer100g: 90, sugar_g: 13.0, fat_g: 1.5, protein_g: 1.5, processed: true, tags: [] },
{ name: "Lemon Ice Tea", category: "drink", caloriesPer100g: 28, sugar_g: 7.0, fat_g: 0, protein_g: 0, processed: true, tags: [] },

// Extra International
{ name: "Fajitas", category: "mexican", caloriesPer100g: 200, sugar_g: 3.0, fat_g: 9.0, protein_g: 14.0, processed: true, tags: [] },
{ name: "Enchiladas", category: "mexican", caloriesPer100g: 225, sugar_g: 3.0, fat_g: 10.0, protein_g: 13.0, processed: true, tags: [] },
{ name: "Mac and Cheese", category: "western", caloriesPer100g: 310, sugar_g: 3.0, fat_g: 18.0, protein_g: 11.0, processed: true, tags: ["junk"] },
{ name: "Beef Taco", category: "mexican", caloriesPer100g: 240, sugar_g: 2.0, fat_g: 12.0, protein_g: 12.0, processed: true, tags: ["junk"] },
{ name: "Veg Ramen", category: "japanese", caloriesPer100g: 160, sugar_g: 2.0, fat_g: 4.0, protein_g: 6.0, processed: true, tags: [] },
{ name: "Chicken Gyro", category: "mediterranean", caloriesPer100g: 220, sugar_g: 2.0, fat_g: 9.0, protein_g: 16.0, processed: true, tags: [] },
{ name: "Seafood Paella", category: "spanish", caloriesPer100g: 185, sugar_g: 1.0, fat_g: 6.0, protein_g: 12.0, processed: true, tags: ["seafood"] },
{ name: "Bruschetta", category: "italian", caloriesPer100g: 170, sugar_g: 1.5, fat_g: 7.0, protein_g: 4.0, processed: true, tags: [] },
{ name: "Stuffed Peppers", category: "healthy", caloriesPer100g: 120, sugar_g: 3.5, fat_g: 3.0, protein_g: 4.0, processed: false, tags: [] },
{ name: "Chicken Quesadilla", category: "mexican", caloriesPer100g: 245, sugar_g: 2.0, fat_g: 14.0, protein_g: 15.0, processed: true, tags: [] },
// ---- PART 4: Foods 1151–1350 ----

// Indian Street Food
{ name: "Dahi Puri", category: "snack", caloriesPer100g: 215, sugar_g: 3.5, fat_g: 8.0, protein_g: 4.0, processed: true, tags: [] },
{ name: "Sev Puri", category: "snack", caloriesPer100g: 240, sugar_g: 4.0, fat_g: 10.0, protein_g: 3.0, processed: true, tags: ["junk"] },
{ name: "Ragda Pattice", category: "snack", caloriesPer100g: 235, sugar_g: 3.0, fat_g: 8.0, protein_g: 5.0, processed: true, tags: [] },
{ name: "Soya Chaap Roll", category: "snack", caloriesPer100g: 260, sugar_g: 2.0, fat_g: 12.0, protein_g: 14.0, processed: true, tags: ["protein_rich"] },
{ name: "Chicken Lollipop", category: "snack", caloriesPer100g: 300, sugar_g: 2.0, fat_g: 17.0, protein_g: 18.0, processed: true, tags: ["fried"] },
{ name: "Chole Kulche", category: "north indian", caloriesPer100g: 290, sugar_g: 4.0, fat_g: 9.0, protein_g: 10.0, processed: true, tags: [] },
{ name: "Vada Sambar", category: "south indian", caloriesPer100g: 240, sugar_g: 1.0, fat_g: 11.0, protein_g: 6.0, processed: true, tags: [] },
{ name: "Bhel Puri Sev Mix", category: "snack", caloriesPer100g: 250, sugar_g: 4.0, fat_g: 8.0, protein_g: 4.0, processed: true, tags: [] },
{ name: "Dabeli", category: "snack", caloriesPer100g: 295, sugar_g: 5.0, fat_g: 9.0, protein_g: 6.0, processed: true, tags: ["junk"] },
{ name: "Chicken Shawarma Roll", category: "snack", caloriesPer100g: 270, sugar_g: 4.0, fat_g: 12.0, protein_g: 16.0, processed: true, tags: [] },

// Fast Food
{ name: "Veggie Nuggets", category: "fast food", caloriesPer100g: 250, sugar_g: 2.0, fat_g: 13.0, protein_g: 9.0, processed: true, tags: [] },
{ name: "Chicken Popcorn", category: "fast food", caloriesPer100g: 290, sugar_g: 2.0, fat_g: 15.0, protein_g: 15.0, processed: true, tags: ["fried"] },
{ name: "Beef Hot Dog", category: "fast food", caloriesPer100g: 305, sugar_g: 3.0, fat_g: 17.0, protein_g: 12.0, processed: true, tags: ["junk"] },
{ name: "Chicken Submarine", category: "fast food", caloriesPer100g: 235, sugar_g: 3.0, fat_g: 9.0, protein_g: 14.0, processed: true, tags: [] },
{ name: "Cheesy Garlic Pizza", category: "fast food", caloriesPer100g: 285, sugar_g: 5.0, fat_g: 12.0, protein_g: 13.0, processed: true, tags: [] },
{ name: "Loaded Nachos", category: "mexican", caloriesPer100g: 320, sugar_g: 3.0, fat_g: 18.0, protein_g: 7.0, processed: true, tags: ["junk"] },
{ name: "BBQ Burger", category: "fast food", caloriesPer100g: 310, sugar_g: 6.0, fat_g: 16.0, protein_g: 18.0, processed: true, tags: ["junk"] },
{ name: "Stuffed Crust Pizza", category: "fast food", caloriesPer100g: 300, sugar_g: 4.0, fat_g: 15.0, protein_g: 12.0, processed: true, tags: [] },
{ name: "Crispy Chicken Burger", category: "fast food", caloriesPer100g: 310, sugar_g: 5.0, fat_g: 18.0, protein_g: 14.0, processed: true, tags: ["fried"] },
{ name: "Veggie Sub", category: "fast food", caloriesPer100g: 205, sugar_g: 2.0, fat_g: 7.0, protein_g: 11.0, processed: true, tags: [] },

// Fruits
{ name: "Lychee", category: "fruit", caloriesPer100g: 66, sugar_g: 15.0, fat_g: 0.4, protein_g: 0.8, processed: false, tags: ["fruit"] },
{ name: "Blackberries", category: "fruit", caloriesPer100g: 43, sugar_g: 4.9, fat_g: 0.3, protein_g: 1.4, processed: false, tags: ["fruit"] },
{ name: "Cherries", category: "fruit", caloriesPer100g: 50, sugar_g: 11.0, fat_g: 0.3, protein_g: 1.0, processed: false, tags: ["fruit"] },
{ name: "Pomegranate", category: "fruit", caloriesPer100g: 83, sugar_g: 13.7, fat_g: 1.2, protein_g: 1.7, processed: false, tags: ["fruit"] },
{ name: "Dragon Fruit", category: "fruit", caloriesPer100g: 60, sugar_g: 9.0, fat_g: 0.1, protein_g: 1.2, processed: false, tags: ["fruit"] },
{ name: "Custard Apple", category: "fruit", caloriesPer100g: 94, sugar_g: 18.0, fat_g: 0.5, protein_g: 2.1, processed: false, tags: ["fruit"] },
{ name: "Pear", category: "fruit", caloriesPer100g: 57, sugar_g: 10.0, fat_g: 0.1, protein_g: 0.4, processed: false, tags: ["fruit"] },
{ name: "Guava", category: "fruit", caloriesPer100g: 68, sugar_g: 9.0, fat_g: 1.0, protein_g: 3.0, processed: false, tags: [] },
{ name: "Raspberry", category: "fruit", caloriesPer100g: 52, sugar_g: 4.4, fat_g: 0.7, protein_g: 1.2, processed: false, tags: [] },
{ name: "Cantaloupe", category: "fruit", caloriesPer100g: 34, sugar_g: 8.0, fat_g: 0.2, protein_g: 0.8, processed: false, tags: [] },

// Vegetables
{ name: "Pumpkin Sabzi", category: "vegetable", caloriesPer100g: 40, sugar_g: 3.5, fat_g: 2.0, protein_g: 1.0, processed: false, tags: [] },
{ name: "Beans Poriyal", category: "vegetable", caloriesPer100g: 60, sugar_g: 2.0, fat_g: 3.0, protein_g: 2.0, processed: false, tags: [] },
{ name: "Bitter Gourd Fry", category: "vegetable", caloriesPer100g: 145, sugar_g: 1.5, fat_g: 8.0, protein_g: 3.0, processed: true, tags: [] },
{ name: "Aloo Gobi", category: "vegetable", caloriesPer100g: 80, sugar_g: 2.0, fat_g: 3.0, protein_g: 2.0, processed: false, tags: [] },
{ name: "Bhindi Fry", category: "vegetable", caloriesPer100g: 140, sugar_g: 2.0, fat_g: 8.0, protein_g: 2.0, processed: true, tags: [] },
{ name: "Carrot Peas Sabzi", category: "vegetable", caloriesPer100g: 70, sugar_g: 3.0, fat_g: 2.0, protein_g: 3.0, processed: false, tags: [] },
{ name: "Paneer Capsicum Fry", category: "vegetable", caloriesPer100g: 180, sugar_g: 3.0, fat_g: 10.0, protein_g: 9.0, processed: true, tags: [] },
{ name: "Methi Sabzi", category: "vegetable", caloriesPer100g: 76, sugar_g: 2.0, fat_g: 4.0, protein_g: 3.5, processed: false, tags: [] },
{ name: "Bottle Gourd Curry", category: "vegetable", caloriesPer100g: 65, sugar_g: 2.5, fat_g: 3.0, protein_g: 2.5, processed: false, tags: [] },
{ name: "Mushroom Masala", category: "vegetable", caloriesPer100g: 150, sugar_g: 2.0, fat_g: 8.0, protein_g: 5.0, processed: true, tags: [] },

// Soups
{ name: "Corn Chicken Soup", category: "soup", caloriesPer100g: 65, sugar_g: 3.0, fat_g: 2.0, protein_g: 5.0, processed: true, tags: [] },
{ name: "Paneer Soup", category: "soup", caloriesPer100g: 85, sugar_g: 2.0, fat_g: 4.0, protein_g: 7.0, processed: true, tags: ["protein_rich"] },
{ name: "Spinach Soup", category: "soup", caloriesPer100g: 45, sugar_g: 3.0, fat_g: 1.0, protein_g: 3.0, processed: true, tags: ["healthy"] },
{ name: "Chicken Manchow Soup", category: "soup", caloriesPer100g: 75, sugar_g: 3.0, fat_g: 4.0, protein_g: 6.0, processed: true, tags: [] },
{ name: "Sweet Corn Veg Soup", category: "soup", caloriesPer100g: 55, sugar_g: 4.0, fat_g: 1.0, protein_g: 1.5, processed: true, tags: [] },
{ name: "Tom Yum Soup", category: "thai", caloriesPer100g: 55, sugar_g: 2.0, fat_g: 1.0, protein_g: 4.0, processed: false, tags: [] },
{ name: "Beef Soup", category: "western", caloriesPer100g: 70, sugar_g: 2.0, fat_g: 3.0, protein_g: 8.0, processed: false, tags: [] },
{ name: "Mulligatawny Soup", category: "indian", caloriesPer100g: 80, sugar_g: 3.5, fat_g: 3.0, protein_g: 3.5, processed: false, tags: [] },
{ name: "Veg Clear Soup Special", category: "soup", caloriesPer100g: 32, sugar_g: 2.0, fat_g: 0.4, protein_g: 1.1, processed: false, tags: [] },
{ name: "Creamy Mushroom Soup", category: "soup", caloriesPer100g: 85, sugar_g: 3.0, fat_g: 5.0, protein_g: 4.0, processed: true, tags: [] },

// Mediterranean & Arabic
{ name: "Kibbeh", category: "middle eastern", caloriesPer100g: 277, sugar_g: 1.5, fat_g: 17.0, protein_g: 14.0, processed: true, tags: [] },
{ name: "Tabbouleh", category: "healthy", caloriesPer100g: 80, sugar_g: 1.5, fat_g: 3.0, protein_g: 2.0, processed: false, tags: [] },
{ name: "Chicken Tagine", category: "middle eastern", caloriesPer100g: 135, sugar_g: 1.0, fat_g: 7.0, protein_g: 15.0, processed: true, tags: [] },
{ name: "Zaatar Bread", category: "middle eastern", caloriesPer100g: 310, sugar_g: 3.0, fat_g: 15.0, protein_g: 12.0, processed: true, tags: [] },
{ name: "Labneh Dip", category: "mediterranean", caloriesPer100g: 150, sugar_g: 3.0, fat_g: 8.0, protein_g: 10.0, processed: false, tags: [] },
{ name: "Shakshuka", category: "mediterranean", caloriesPer100g: 120, sugar_g: 3.0, fat_g: 7.0, protein_g: 6.0, processed: false, tags: [] },
// ---- PART 4: Foods 1351–1550 ----

// Indian Meals**
{ name: "Rajma Chawal", category: "north indian", caloriesPer100g: 180, sugar_g: 2.5, fat_g: 3.5, protein_g: 6.5, processed: false, tags: ["protein_rich"] },
{ name: "Dal Tadka", category: "north indian", caloriesPer100g: 175, sugar_g: 1.8, fat_g: 6.0, protein_g: 7.0, processed: false, tags: [] },
{ name: "Jeera Rice", category: "rice", caloriesPer100g: 160, sugar_g: 0.5, fat_g: 4.0, protein_g: 3.0, processed: false, tags: [] },
{ name: "Veg Pulao", category: "rice", caloriesPer100g: 180, sugar_g: 1.0, fat_g: 6.0, protein_g: 4.0, processed: false, tags: [] },
{ name: "Chicken Pulao", category: "rice", caloriesPer100g: 210, sugar_g: 1.0, fat_g: 7.0, protein_g: 11.0, processed: true, tags: ["protein_rich"] },
{ name: "Methi Paratha", category: "bread", caloriesPer100g: 210, sugar_g: 3.0, fat_g: 8.0, protein_g: 5.0, processed: true, tags: [] },
{ name: "Gobi Paratha", category: "bread", caloriesPer100g: 225, sugar_g: 3.0, fat_g: 9.0, protein_g: 6.0, processed: true, tags: [] },
{ name: "Aloo Kulcha", category: "bread", caloriesPer100g: 255, sugar_g: 3.0, fat_g: 10.0, protein_g: 7.0, processed: true, tags: [] },
{ name: "Paneer Kulcha", category: "bread", caloriesPer100g: 270, sugar_g: 3.0, fat_g: 12.0, protein_g: 9.0, processed: true, tags: ["protein_rich"] },
{ name: "Butter Garlic Naan", category: "bread", caloriesPer100g: 300, sugar_g: 3.5, fat_g: 12.0, protein_g: 8.0, processed: true, tags: ["junk"] },

// International Popular
{ name: "Chicken Burrito Bowl", category: "mexican", caloriesPer100g: 225, sugar_g: 2.0, fat_g: 11.0, protein_g: 16.0, processed: true, tags: [] },
{ name: "Veg Tortilla Wrap", category: "mexican", caloriesPer100g: 210, sugar_g: 2.0, fat_g: 9.0, protein_g: 7.0, processed: true, tags: [] },
{ name: "Beef Fajita", category: "mexican", caloriesPer100g: 240, sugar_g: 3.0, fat_g: 11.0, protein_g: 14.0, processed: true, tags: [] },
{ name: "Vegetable Paella", category: "spanish", caloriesPer100g: 180, sugar_g: 1.0, fat_g: 6.0, protein_g: 5.0, processed: false, tags: [] },
{ name: "Churros", category: "dessert", caloriesPer100g: 430, sugar_g: 25.0, fat_g: 23.0, protein_g: 4.0, processed: true, tags: ["fried", "dessert"] },
{ name: "BBQ Ribs", category: "western", caloriesPer100g: 290, sugar_g: 7.0, fat_g: 18.0, protein_g: 23.0, processed: true, tags: ["high_fat"] },
{ name: "Veg Quesadilla", category: "mexican", caloriesPer100g: 235, sugar_g: 2.0, fat_g: 12.0, protein_g: 10.0, processed: true, tags: [] },
{ name: "Chicken Fajita", category: "mexican", caloriesPer100g: 220, sugar_g: 2.0, fat_g: 8.0, protein_g: 17.0, processed: true, tags: [] },
{ name: "Seafood Risotto", category: "italian", caloriesPer100g: 200, sugar_g: 1.5, fat_g: 7.0, protein_g: 11.0, processed: true, tags: ["seafood"] },
{ name: "Paneer Quesadilla", category: "mexican", caloriesPer100g: 240, sugar_g: 2.0, fat_g: 12.0, protein_g: 10.5, processed: true, tags: [] },

// Fruit Bowls
{ name: "Kiwi Fruit Bowl", category: "healthy", caloriesPer100g: 70, sugar_g: 10.0, fat_g: 0.3, protein_g: 1.3, processed: false, tags: [] },
{ name: "Strawberry Oats Bowl", category: "healthy", caloriesPer100g: 95, sugar_g: 14.0, fat_g: 2.0, protein_g: 3.0, processed: false, tags: [] },
{ name: "Banana Peanut Butter Bowl", category: "healthy", caloriesPer100g: 160, sugar_g: 12.0, fat_g: 8.0, protein_g: 5.0, processed: true, tags: [] },
{ name: "Mango Yogurt Bowl", category: "healthy", caloriesPer100g: 140, sugar_g: 16.0, fat_g: 2.5, protein_g: 3.5, processed: true, tags: [] },
{ name: "Fresh Fruit Medley", category: "healthy", caloriesPer100g: 65, sugar_g: 12.0, fat_g: 0.3, protein_g: 1.0, processed: false, tags: [] },
{ name: "Protein Fruit Bowl", category: "healthy", caloriesPer100g: 110, sugar_g: 9.0, fat_g: 3.0, protein_g: 9.0, processed: false, tags: ["protein_rich"] },
{ name: "Avocado Kiwi Bowl", category: "healthy", caloriesPer100g: 150, sugar_g: 8.0, fat_g: 9.0, protein_g: 3.0, processed: false, tags: [] },
{ name: "Apple Cinnamon Bowl", category: "healthy", caloriesPer100g: 100, sugar_g: 15.0, fat_g: 2.0, protein_g: 1.0, processed: true, tags: [] },
{ name: "Berry Smoothie Bowl", category: "healthy", caloriesPer100g: 120, sugar_g: 18.0, fat_g: 2.0, protein_g: 2.5, processed: true, tags: [] },
{ name: "Papaya Fruit Bowl", category: "healthy", caloriesPer100g: 75, sugar_g: 10.0, fat_g: 0.5, protein_g: 1.2, processed: false, tags: [] },

// Soups & Stews
{ name: "Chicken Vegetable Stew", category: "western", caloriesPer100g: 110, sugar_g: 4.0, fat_g: 4.0, protein_g: 9.0, processed: false, tags: [] },
{ name: "Lamb Stew", category: "western", caloriesPer100g: 130, sugar_g: 3.0, fat_g: 5.0, protein_g: 11.0, processed: false, tags: [] },
{ name: "Veg Bean Stew", category: "western", caloriesPer100g: 95, sugar_g: 3.0, fat_g: 3.0, protein_g: 6.0, processed: false, tags: [] },
{ name: "Seafood Chowder", category: "seafood", caloriesPer100g: 200, sugar_g: 2.0, fat_g: 10.0, protein_g: 14.0, processed: true, tags: [] },
{ name: "Chicken Barley Soup", category: "soup", caloriesPer100g: 60, sugar_g: 3.0, fat_g: 1.0, protein_g: 6.0, processed: false, tags: [] },
{ name: "Tomato Basil Soup", category: "soup", caloriesPer100g: 35, sugar_g: 4.0, fat_g: 1.0, protein_g: 1.0, processed: false, tags: [] },
{ name: "Mutton Keema Stew", category: "protein", caloriesPer100g: 260, sugar_g: 1.0, fat_g: 18.0, protein_g: 16.0, processed: true, tags: ["protein_rich"] },
{ name: "Broccoli Soup", category: "soup", caloriesPer100g: 50, sugar_g: 1.5, fat_g: 1.0, protein_g: 3.5, processed: false, tags: ["healthy"] },
{ name: "Miso Veg Soup", category: "japanese", caloriesPer100g: 38, sugar_g: 2.0, fat_g: 1.0, protein_g: 2.5, processed: true, tags: [] },
{ name: "Pumpkin Lentil Soup", category: "healthy", caloriesPer100g: 65, sugar_g: 3.0, fat_g: 2.0, protein_g: 3.0, processed: false, tags: [] },

// More Global Foods
{ name: "Sweet Potato Fries", category: "western", caloriesPer100g: 300, sugar_g: 14.0, fat_g: 15.0, protein_g: 2.0, processed: true, tags: ["fried"] },
{ name: "Veggie Rice Bowl", category: "healthy", caloriesPer100g: 150, sugar_g: 3.0, fat_g: 4.0, protein_g: 4.0, processed: false, tags: [] },
{ name: "Egg Rice Bowl", category: "asian", caloriesPer100g: 180, sugar_g: 1.0, fat_g: 6.0, protein_g: 7.0, processed: true, tags: [] },
{ name: "Chicken Curry Rice Bowl", category: "protein", caloriesPer100g: 225, sugar_g: 2.5, fat_g: 9.0, protein_g: 15.0, processed: true, tags: [] },
{ name: "Tofu Rice Bowl", category: "healthy", caloriesPer100g: 160, sugar_g: 1.5, fat_g: 5.0, protein_g: 8.0, processed: false, tags: [] },
{ name: "Sausage Rice Bowl", category: "fast food", caloriesPer100g: 250, sugar_g: 1.0, fat_g: 12.0, protein_g: 12.0, processed: true, tags: [] },
{ name: "Chicken Teriyaki Rice Bowl", category: "asian", caloriesPer100g: 210, sugar_g: 3.0, fat_g: 8.0, protein_g: 16.0, processed: true, tags: [] },
{ name: "Cauliflower Couscous Bowl", category: "healthy", caloriesPer100g: 55, sugar_g: 3.0, fat_g: 1.0, protein_g: 2.0, processed: false, tags: [] },
{ name: "Shrimp Rice Bowl", category: "seafood", caloriesPer100g: 200, sugar_g: 1.0, fat_g: 6.0, protein_g: 16.0, processed: true, tags: ["seafood"] },
{ name: "Veggie Lentil Bowl", category: "healthy", caloriesPer100g: 120, sugar_g: 2.0, fat_g: 3.0, protein_g: 6.0, processed: false, tags: [] }
];
